In [72]:
import pandas as pd
pd.set_option('display.max_columns', 1500)

import warnings
warnings.filterwarnings('ignore')

#Extend cell width
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

In [73]:
df = pd.read_csv("D:/Work/Gre/UTD/Courses/Fall/MIS6341/Softwares/Python/ml-fall-2023/Project2/SBA_loans_project_2.csv")
df.drop(columns="index",inplace=True)

In [74]:
df

City State    Zip                            Bank  \
0              NEW YORK    NY  10003  JPMORGAN CHASE BANK NATL ASSOC   
1             PAWTUCKET    RI   2860        CITIZENS BANK NATL ASSOC   
2              ISSAQUAH    WA  98027       FIRST-CITIZENS BK & TR CO   
3                 HURST    TX  76053                   WILSHIRE BANK   
4                ALPINE    CA  91901         CALIFORNIA BANK & TRUST   
...                 ...   ...    ...                             ...   
800250          Kenmore    NY  14217    KEYBANK NATIONAL ASSOCIATION   
800251  MENOMONEE FALLS    WI  53051             WAUKESHA STATE BANK   
800252         LONGVIEW    TX  75604          CAPITAL ONE NATL ASSOC   
800253           CAMDEN    NJ   8105      BANK OF AMERICA NATL ASSOC   
800254         COVENTRY    RI   2816        CITIZENS BANK NATL ASSOC   

       BankState   NAICS  NoEmp  NewExist  CreateJob  RetainedJob  \
0             IL  561439      9       1.0          1            9   
1             RI  541810      8       1.0          4           12   
2             WA  448210      9       2.0          0            0   
3             CA  722213      4       1.0          0            4   
4             CA  233210      1       1.0          0            1   
...          ...     ...    ...       ...        ...          ...   
800250        OH  561720    112       1.0          0            0   
800251        WI  337110     75       1.0          0           75   
800252        VA  517310      2       1.0          0            0   
800253        RI  447110      4       2.0          0            0   
800254        RI  541511      1       1.0          0            1   

        FranchiseCode  UrbanRural RevLineCr LowDoc  DisbursementGross  \
0                   1           1         0      N            68000.0   
1                   0           1         N      N            90000.0   
2                   1           0         N      N           450000.0   
3                   1           1         0      N           140000.0   
4                   1           2         Y      N            50000.0   
...               ...         ...       ...    ...                ...   
800250              1           1         N      N            45500.0   
800251              1           1         0      N           550000.0   
800252              1           1         0      Y           128800.0   
800253              1           1         Y      N           100000.0   
800254              0           1         N      N            10000.0   

        BalanceGross    GrAppv  SBA_Appv  MIS_Status  
0                0.0   68000.0   34000.0           0  
1                0.0   90000.0   45000.0           1  
2                0.0  450000.0  337500.0           0  
3                0.0  165000.0   82500.0           0  
4                0.0   50000.0   25000.0           0  
...              ...       ...       ...         ...  
800250           0.0   45500.0   22750.0           0  
800251           0.0  550000.0  412500.0           0  
800252           0.0  135000.0  114750.0           0  
800253           0.0  100000.0   50000.0           0  
800254           0.0   10000.0    5000.0           0  

[800255 rows x 19 columns]

In [75]:
df.isnull().sum()

City                   26
State                  13
Zip                     0
Bank                 1381
BankState            1386
NAICS                   0
NoEmp                   0
NewExist              127
CreateJob               0
RetainedJob             0
FranchiseCode           0
UrbanRural              0
RevLineCr            4016
LowDoc               2316
DisbursementGross       0
BalanceGross            0
GrAppv                  0
SBA_Appv                0
MIS_Status              0
dtype: int64

In [76]:
#show unique values in each column and its data type
for col in df.columns:
    print(f'{col} unique values are {df[col].unique()}')
    print("\n")
    print(f'{col} data type is {df[col].dtype}')

City unique values are ['NEW YORK' 'PAWTUCKET' 'ISSAQUAH' ... 'ST  FRANCIS' 'Stevens point'
 'Pylesville']


City data type is object
State unique values are ['NY' 'RI' 'WA' 'TX' 'CA' 'NC' 'MN' 'MO' 'FL' 'IA' 'IL' 'DC' 'PA' 'AL'
 'MS' 'OH' 'MA' 'NJ' 'ME' 'NV' 'LA' 'MI' 'IN' 'GA' 'UT' 'VA' 'WI' 'TN'
 'KS' 'NH' 'CO' 'CT' 'KY' 'AZ' 'ID' 'DE' 'SD' 'AR' 'MD' 'OK' 'SC' 'NM'
 'MT' 'NE' 'OR' 'WY' 'AK' 'HI' 'VT' 'ND' 'WV' nan]


State data type is object
Zip unique values are [10003  2860 98027 ... 78944 17814 95812]


Zip data type is int64
Bank unique values are ['JPMORGAN CHASE BANK NATL ASSOC' 'CITIZENS BANK NATL ASSOC'
 'FIRST-CITIZENS BK & TR CO' ... 'TULSA NATIONAL BANCSHARES, INC'
 'BEACH PLAZA LLC' 'THE LEADERS BANK']


Bank data type is object
BankState unique values are ['IL' 'RI' 'WA' 'CA' 'NC' 'MN' 'MO' 'OR' 'FL' 'IA' 'SD' 'DC' 'TX' 'PA'
 'VA' 'AL' 'OH' 'MS' 'IN' 'MA' 'ME' 'MI' 'DE' 'UT' 'SC' 'NY' 'KS' 'CO'
 'LA' 'WI' 'CT' 'AZ' 'AR' 'MD' 'OK' 'NM' 'ID' 'MT' 'NJ' 'KY' 'NE' 'WY'
 'GA

In [77]:
df

City State    Zip                            Bank  \
0              NEW YORK    NY  10003  JPMORGAN CHASE BANK NATL ASSOC   
1             PAWTUCKET    RI   2860        CITIZENS BANK NATL ASSOC   
2              ISSAQUAH    WA  98027       FIRST-CITIZENS BK & TR CO   
3                 HURST    TX  76053                   WILSHIRE BANK   
4                ALPINE    CA  91901         CALIFORNIA BANK & TRUST   
...                 ...   ...    ...                             ...   
800250          Kenmore    NY  14217    KEYBANK NATIONAL ASSOCIATION   
800251  MENOMONEE FALLS    WI  53051             WAUKESHA STATE BANK   
800252         LONGVIEW    TX  75604          CAPITAL ONE NATL ASSOC   
800253           CAMDEN    NJ   8105      BANK OF AMERICA NATL ASSOC   
800254         COVENTRY    RI   2816        CITIZENS BANK NATL ASSOC   

       BankState   NAICS  NoEmp  NewExist  CreateJob  RetainedJob  \
0             IL  561439      9       1.0          1            9   
1             RI  541810      8       1.0          4           12   
2             WA  448210      9       2.0          0            0   
3             CA  722213      4       1.0          0            4   
4             CA  233210      1       1.0          0            1   
...          ...     ...    ...       ...        ...          ...   
800250        OH  561720    112       1.0          0            0   
800251        WI  337110     75       1.0          0           75   
800252        VA  517310      2       1.0          0            0   
800253        RI  447110      4       2.0          0            0   
800254        RI  541511      1       1.0          0            1   

        FranchiseCode  UrbanRural RevLineCr LowDoc  DisbursementGross  \
0                   1           1         0      N            68000.0   
1                   0           1         N      N            90000.0   
2                   1           0         N      N           450000.0   
3                   1           1         0      N           140000.0   
4                   1           2         Y      N            50000.0   
...               ...         ...       ...    ...                ...   
800250              1           1         N      N            45500.0   
800251              1           1         0      N           550000.0   
800252              1           1         0      Y           128800.0   
800253              1           1         Y      N           100000.0   
800254              0           1         N      N            10000.0   

        BalanceGross    GrAppv  SBA_Appv  MIS_Status  
0                0.0   68000.0   34000.0           0  
1                0.0   90000.0   45000.0           1  
2                0.0  450000.0  337500.0           0  
3                0.0  165000.0   82500.0           0  
4                0.0   50000.0   25000.0           0  
...              ...       ...       ...         ...  
800250           0.0   45500.0   22750.0           0  
800251           0.0  550000.0  412500.0           0  
800252           0.0  135000.0  114750.0           0  
800253           0.0  100000.0   50000.0           0  
800254           0.0   10000.0    5000.0           0  

[800255 rows x 19 columns]

In [78]:
for i in df['RevLineCr']:
    if i not in ['Y','N']:
        df['RevLineCr'].replace(i,'N',inplace=True)
print("RevLineCr",df['RevLineCr'].unique())

for i in df['LowDoc']:
    if i not in ['Y','N']:
        df['LowDoc'].replace(i,'N',inplace=True)
print("LowDoc",df['LowDoc'].unique())

for i in df['NewExist']:
    if i not in [1,2]:
        df['NewExist'].replace(i,None,inplace=True)
print("NewExist",df['NewExist'].unique())

RevLineCr ['N' 'Y']
LowDoc ['N' 'Y']
NewExist [1.0 2.0 None]


In [79]:
df.isnull().sum()

City                   26
State                  13
Zip                     0
Bank                 1381
BankState            1386
NAICS                   0
NoEmp                   0
NewExist             1057
CreateJob               0
RetainedJob             0
FranchiseCode           0
UrbanRural              0
RevLineCr               0
LowDoc                  0
DisbursementGross       0
BalanceGross            0
GrAppv                  0
SBA_Appv                0
MIS_Status              0
dtype: int64

In [80]:
category_cols=['City', 'State', 'Bank', 'BankState', 'RevLineCr', 'LowDoc','NewExist']
for column in category_cols:
  df[column]=df[column].fillna(df[column].mode()[0])

In [81]:
df.isnull().sum()

City                 0
State                0
Zip                  0
Bank                 0
BankState            0
NAICS                0
NoEmp                0
NewExist             0
CreateJob            0
RetainedJob          0
FranchiseCode        0
UrbanRural           0
RevLineCr            0
LowDoc               0
DisbursementGross    0
BalanceGross         0
GrAppv               0
SBA_Appv             0
MIS_Status           0
dtype: int64

In [82]:
from sklearn.model_selection import train_test_split

X_train,X_test = train_test_split(df,test_size=0.3,random_state=123)
X_train.shape, X_test.shape

((560178, 19), (240077, 19))

``` Training set has 560178 rows and testing set has 240077 samples

Target encoding is a data preprocessing technique used to convert categorical variables into numerical values that can be used by machine learning algorithms. It works by replacing each category with the average value of the target variable for that category. This can be helpful for algorithms that cannot handle categorical variables directly.

In this case the target variable is "MIS_Status"```

In [83]:
# Target encoder
import category_encoders as ce
categorical_columns = ['City', 'State', 'Bank', 'BankState', 'RevLineCr', 'LowDoc','NewExist', 'UrbanRural']

encoder = ce.TargetEncoder(cols=categorical_columns)
encoder.fit(X_train, X_train['MIS_Status'])

train_encoded = encoder.transform(X_train)
test_encoded = encoder.transform(X_test)

# Renaming the columns
train_encoded.rename(columns={col: col + "_trg" if col in categorical_columns else col for col in train_encoded.columns}, inplace=False)
test_encoded.rename(columns={col: col + "_trg" if col in categorical_columns else col for col in test_encoded.columns}, inplace=False)

train_encoded.head()

City     State    Zip      Bank  BankState   NAICS  NoEmp  \
148172  0.215946  0.165802  45648  0.740692   0.217642  452990      2   
744579  0.226933  0.165802  43240  0.133135   0.158188  445310      7   
321200  0.252778  0.196143  21037  0.194430   0.076619       0      3   
74901   0.275938  0.184227  90071  0.141177   0.178801  541310     12   
426895  0.057056  0.184227  95037  0.412096   0.380604  561720      1   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
148172   0.17067          2            2              0    0.186517   
744579   0.17067          0            0              0    0.243731   
321200   0.17067          0            0              1    0.070886   
74901    0.17067         12           12              1    0.243731   
426895   0.17067          0            1              0    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
148172   0.152625  0.186815            12500.0           0.0   12500.0   
744579   0.152625  0.186815            20000.0           0.0   20000.0   
321200   0.152625  0.089154            25000.0           0.0   25000.0   
74901    0.251879  0.186815           985500.0           0.0  350000.0   
426895   0.152625  0.186815            50000.0           0.0   50000.0   

        SBA_Appv  MIS_Status  
148172   10625.0           1  
744579   10000.0           0  
321200   20000.0           0  
74901   175000.0           1  
426895   25000.0           0

In [85]:
train_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 560178 entries, 148172 to 773630
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   City               560178 non-null  float64
 1   State              560178 non-null  float64
 2   Zip                560178 non-null  int64  
 3   Bank               560178 non-null  float64
 4   BankState          560178 non-null  float64
 5   NAICS              560178 non-null  int64  
 6   NoEmp              560178 non-null  int64  
 7   NewExist           560178 non-null  float64
 8   CreateJob          560178 non-null  int64  
 9   RetainedJob        560178 non-null  int64  
 10  FranchiseCode      560178 non-null  int64  
 11  UrbanRural         560178 non-null  float64
 12  RevLineCr          560178 non-null  float64
 13  LowDoc             560178 non-null  float64
 14  DisbursementGross  560178 non-null  float64
 15  BalanceGross       560178 non-null  float64
 16  Gr

StandardScaler in scikit-learn is a preprocessing technique that centers and scales numerical features such that they have a mean of zero and a standard deviation of one.

We will make use of the StandardScaler, which is used to transform both the training and test data in the same way, ensuring that the features have the same mean and standard deviation in both datasets.

Here we will scale it on the training set and transform on both training and testing

In [86]:
from sklearn.preprocessing import StandardScaler
from copy import deepcopy

numerical_columns = [ 'NoEmp', 'CreateJob', 'RetainedJob', 'GrAppv', 'SBA_Appv', 'DisbursementGross', 'BalanceGross']
scaler = StandardScaler()
train_encoded[numerical_columns] = scaler.fit_transform(train_encoded[numerical_columns])
test_encoded[numerical_columns] = scaler.transform(test_encoded[numerical_columns])

train_encoded.head()


City     State    Zip      Bank  BankState   NAICS     NoEmp  \
148172  0.215946  0.165802  45648  0.740692   0.217642  452990 -0.123748   
744579  0.226933  0.165802  43240  0.133135   0.158188  445310 -0.058247   
321200  0.252778  0.196143  21037  0.194430   0.076619       0 -0.110648   
74901   0.275938  0.184227  90071  0.141177   0.178801  541310  0.007255   
426895  0.057056  0.184227  95037  0.412096   0.380604  561720 -0.136849   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
148172   0.17067  -0.026808    -0.036871              0    0.186517   
744579   0.17067  -0.035352    -0.045405              0    0.243731   
321200   0.17067  -0.035352    -0.045405              1    0.070886   
74901    0.17067   0.015917     0.005801              1    0.243731   
426895   0.17067  -0.035352    -0.041138              0    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
148172   0.152625  0.186815          -0.654946     -0.002095 -0.635102   
744579   0.152625  0.186815          -0.628851     -0.002095 -0.608622   
321200   0.152625  0.089154          -0.611454     -0.002095 -0.590969   
74901    0.251879  0.186815           2.730474     -0.002095  0.556485   
426895   0.152625  0.186815          -0.524470     -0.002095 -0.502703   

        SBA_Appv  MIS_Status  
148172 -0.606817           1  
744579 -0.609553           0  
321200 -0.565780           0  
74901   0.112702           1  
426895 -0.543894           0

We have created Feature extraction by making use of old variables in the following way


(1) Log_Disbursement which gives the natural logarithmic form of DisbursementGross variable

(2) Log_GrAppv the logarithmic version of the approved loan amount by the bank

(3) Log_SBA_Appv, the logarithmic amount of the approved loan that will be assisted by SBA 

(4) Log_BalanceGross, is the logarithmic amount of total amount in an account or the total value of a financial asset or liability before any deductions or adjustments are made.

(5) TotalJobs variable which is an addition of Createjobs(New people recruited) and RetainedJob (workers working before)

(6) IncomeToLoan its values are calculated by dividing the 'DisbursementGross' column by the 'SBA_Appv' column for each corresponding row. This ratio can help you analyze the relationship between the amount disbursed and the approved SBA loan amount in terms of income.

(7)  EmployeesToLoanRatio, its values are calculated by dividing the 'NoEmp' column (number of employees) by the 'SBA_Appv' column (approved SBA loan amount) for each corresponding row. This ratio can help you analyze the relationship between the number of employees and the size of the SBA loan approved for each entry in the dataset.

(8) JobPerLoan, its values are calculated by dividing the 'TotalJobs' column (representing the total number of jobs) by the 'SBA_Appv' column (approved SBA loan amount) for each corresponding row. This ratio can help you analyze the impact of the SBA loan on job creation or support, expressed as the number of jobs per unit of loan amount approved.

(9) Gauren_SBA_Appv, Its values are calculated by dividing the 'GrAppv' column (gross amount approved by the lender) by the 'SBA_Appv' column (the approved SBA loan amount) for each corresponding row. This ratio helps you analyze the extent to which the SBA is guaranteeing the loan relative to the total loan amount approved by the lender.

(10) DefaultRate, Finally, we create a new feature 'DefaultRate' in the 'train_encoded' DataFrame and set its value to the calculated default rate for the particular group of loans based on the "MIS_Status" variable. This feature will represent the percentage of loans in the group that are classified as defaults.

In [87]:
# Adding Features
import numpy as np
# Apply the log transformation to the specific feature in your training data
#small_constant = 1e-10  # You can adjust this constant as needed
# df['LogColumn'] = np.log(df['OriginalColumn'] + small_constant)
train_encoded['Log_DisbursementGross'] = np.log1p(train_encoded['DisbursementGross'])
train_encoded['Log_GrAppv'] = np.log1p(train_encoded['GrAppv'])
train_encoded['Log_SBA_Appv'] = np.log1p(train_encoded['SBA_Appv'])
train_encoded['Log_BalanceGross'] = np.log1p(train_encoded['BalanceGross'])
train_encoded['TotalJobs'] = train_encoded['CreateJob'] + train_encoded['RetainedJob']
#train_encoded['Loan_Efficiency'] = train_encoded['DisbursementGross'] / (train_encoded['CreateJob'] + train_encoded['RetainedJob'] + 1)
# Calculate 'LoanToIncomeRatio' as a ratio of 'SBA_Appv' to 'DisbursementGross'
train_encoded['IncomeToLoanRatio'] = train_encoded['DisbursementGross'] / train_encoded['SBA_Appv']
# Calculate 'LoanToEmployeesRatio' as a ratio of 'SBA_Appv' to 'NoEmp'
train_encoded['EmployeesToLoanRatio'] = train_encoded['NoEmp'] / train_encoded['SBA_Appv']
# Create a binary feature to indicate loans with a balance ('BalanceGross' > 0)
#train_encoded['HasBalance'] = (train_encoded['BalanceGross'] > 0).astype(int)
# Calculate 'LoanPerJob' as a ratio of 'SBA_Appv' to 'TotalJobs'
train_encoded['JobPerLoan'] = train_encoded['TotalJobs'] / train_encoded['SBA_Appv'] 
# Calculate SBA's Gaurenteed Portion of Approved Loan
train_encoded['Gauren_SBA_Appv'] = train_encoded['GrAppv'] / train_encoded['SBA_Appv']
# Filter the DataFrame to include only the relevant rows
default_group = train_encoded[train_encoded['MIS_Status'].isin([0, 1])]
# Calculate the total number of loans in the filtered group
total_loans = len(default_group)
# Calculate the number of defaults (CHGOFF) in the filtered group
default_loans = len(default_group[default_group['MIS_Status'] == 1])
# Calculate the default rate as a percentage
default_rate = (default_loans / total_loans) * 100
# Create a new feature 'DefaultRate' with the calculated default rate
train_encoded['DefaultRate'] = default_rate


In [88]:
# Adding Features
import numpy as np
# Apply the log transformation to the specific feature in your training data
#small_constant = 1e-10  # You can adjust this constant as needed
# df['LogColumn'] = np.log(df['OriginalColumn'] + small_constant)
test_encoded['Log_DisbursementGross'] = np.log1p(test_encoded['DisbursementGross'])
test_encoded['Log_GrAppv'] = np.log1p(test_encoded['GrAppv'])
test_encoded['Log_SBA_Appv'] = np.log1p(test_encoded['SBA_Appv'])
test_encoded['Log_BalanceGross'] = np.log1p(test_encoded['BalanceGross'])
test_encoded['TotalJobs'] = test_encoded['CreateJob'] + test_encoded['RetainedJob']
#train_encoded['Loan_Efficiency'] = train_encoded['DisbursementGross'] / (train_encoded['CreateJob'] + train_encoded['RetainedJob'] + 1)
# Calculate 'LoanToIncomeRatio' as a ratio of 'SBA_Appv' to 'DisbursementGross'
test_encoded['IncomeToLoanRatio'] = test_encoded['DisbursementGross'] / test_encoded['SBA_Appv']
# Calculate 'LoanToEmployeesRatio' as a ratio of 'SBA_Appv' to 'NoEmp'
test_encoded['EmployeesToLoanRatio'] = test_encoded['NoEmp'] / test_encoded['SBA_Appv']
# Create a binary feature to indicate loans with a balance ('BalanceGross' > 0)
#train_encoded['HasBalance'] = (train_encoded['BalanceGross'] > 0).astype(int)
# Calculate 'LoanPerJob' as a ratio of 'SBA_Appv' to 'TotalJobs'
test_encoded['JobPerLoan'] = test_encoded['TotalJobs'] / test_encoded['SBA_Appv'] 
# Calculate SBA's Gaurenteed Portion of Approved Loan
test_encoded['Gauren_SBA_Appv'] = test_encoded['GrAppv'] / test_encoded['SBA_Appv']
# Filter the DataFrame to include only the relevant rows
default_group = test_encoded[test_encoded['MIS_Status'].isin([0, 1])]
# Calculate the total number of loans in the filtered group
total_loans = len(default_group)
# Calculate the number of defaults (CHGOFF) in the filtered group
default_loans = len(default_group[default_group['MIS_Status'] == 1])
# Calculate the default rate as a percentage
default_rate = (default_loans / total_loans) * 100
# Create a new feature 'DefaultRate' with the calculated default rate
test_encoded['DefaultRate'] = default_rate


In [89]:
train_encoded.columns

Index(['City', 'State', 'Zip', 'Bank', 'BankState', 'NAICS', 'NoEmp',
       'NewExist', 'CreateJob', 'RetainedJob', 'FranchiseCode', 'UrbanRural',
       'RevLineCr', 'LowDoc', 'DisbursementGross', 'BalanceGross', 'GrAppv',
       'SBA_Appv', 'MIS_Status', 'Log_DisbursementGross', 'Log_GrAppv',
       'Log_SBA_Appv', 'Log_BalanceGross', 'TotalJobs', 'IncomeToLoanRatio',
       'EmployeesToLoanRatio', 'JobPerLoan', 'Gauren_SBA_Appv', 'DefaultRate'],
      dtype='object')

In [90]:
train_encoded.head()

City     State    Zip      Bank  BankState   NAICS     NoEmp  \
148172  0.215946  0.165802  45648  0.740692   0.217642  452990 -0.123748   
744579  0.226933  0.165802  43240  0.133135   0.158188  445310 -0.058247   
321200  0.252778  0.196143  21037  0.194430   0.076619       0 -0.110648   
74901   0.275938  0.184227  90071  0.141177   0.178801  541310  0.007255   
426895  0.057056  0.184227  95037  0.412096   0.380604  561720 -0.136849   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
148172   0.17067  -0.026808    -0.036871              0    0.186517   
744579   0.17067  -0.035352    -0.045405              0    0.243731   
321200   0.17067  -0.035352    -0.045405              1    0.070886   
74901    0.17067   0.015917     0.005801              1    0.243731   
426895   0.17067  -0.035352    -0.041138              0    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
148172   0.152625  0.186815          -0.654946     -0.002095 -0.635102   
744579   0.152625  0.186815          -0.628851     -0.002095 -0.608622   
321200   0.152625  0.089154          -0.611454     -0.002095 -0.590969   
74901    0.251879  0.186815           2.730474     -0.002095  0.556485   
426895   0.152625  0.186815          -0.524470     -0.002095 -0.502703   

        SBA_Appv  MIS_Status  Log_DisbursementGross  Log_GrAppv  Log_SBA_Appv  \
148172 -0.606817           1              -1.064054   -1.008137     -0.933481   
744579 -0.609553           0              -0.991151   -0.938082     -0.940463   
321200 -0.565780           0              -0.945343   -0.893964     -0.834204   
74901   0.112702           1               1.316535    0.442430      0.106791   
426895 -0.543894           0              -0.743325   -0.698569     -0.785029   

        Log_BalanceGross  TotalJobs  IncomeToLoanRatio  EmployeesToLoanRatio  \
148172         -0.002098  -0.063679           1.079313              0.203930   
744579         -0.002098  -0.080758           1.031658              0.095556   
321200         -0.002098  -0.080758           1.080727              0.195567   
74901          -0.002098   0.021717          24.227422              0.064374   
426895         -0.002098  -0.076491           0.964287              0.251609   

        JobPerLoan  Gauren_SBA_Appv  DefaultRate  
148172    0.104939         1.046611    17.487834  
744579    0.132487         0.998473    17.487834  
321200    0.142737         1.044521    17.487834  
74901     0.192698         4.937672    17.487834  
426895    0.140635         0.924268    17.487834

In [91]:
train_encoded

City     State    Zip      Bank  BankState   NAICS     NoEmp  \
148172  0.215946  0.165802  45648  0.740692   0.217642  452990 -0.123748   
744579  0.226933  0.165802  43240  0.133135   0.158188  445310 -0.058247   
321200  0.252778  0.196143  21037  0.194430   0.076619       0 -0.110648   
74901   0.275938  0.184227  90071  0.141177   0.178801  541310  0.007255   
426895  0.057056  0.184227  95037  0.412096   0.380604  561720 -0.136849   
...          ...       ...    ...       ...        ...     ...       ...   
192476  0.148611  0.197720   8882  0.194430   0.253203  238990 -0.045146   
17730   0.097718  0.156276  39601  0.091954   0.097535       0 -0.123748   
28030   0.273994  0.239152  30307  0.269757   0.291471  541213 -0.045146   
277869  0.102190  0.222447  49418  0.246231   0.086229  541690 -0.097548   
773630  0.275938  0.184227  90019  0.077741   0.217642  448120 -0.097548   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
148172  0.170670  -0.026808    -0.036871              0    0.186517   
744579  0.170670  -0.035352    -0.045405              0    0.243731   
321200  0.170670  -0.035352    -0.045405              1    0.070886   
74901   0.170670   0.015917     0.005801              1    0.243731   
426895  0.170670  -0.035352    -0.041138              0    0.243731   
...          ...        ...          ...            ...         ...   
192476  0.185603  -0.031080    -0.011268              1    0.243731   
17730   0.185603  -0.035352    -0.045405              1    0.070886   
28030   0.170670  -0.018263     0.005801              0    0.243731   
277869  0.185603  -0.018263    -0.045405              1    0.243731   
773630  0.170670  -0.035352    -0.028337              1    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
148172   0.152625  0.186815          -0.654946     -0.002095 -0.635102   
744579   0.152625  0.186815          -0.628851     -0.002095 -0.608622   
321200   0.152625  0.089154          -0.611454     -0.002095 -0.590969   
74901    0.251879  0.186815           2.730474     -0.002095  0.556485   
426895   0.152625  0.186815          -0.524470     -0.002095 -0.502703   
...           ...       ...                ...           ...       ...   
192476   0.251879  0.186815          -0.635809     -0.002095 -0.643928   
17730    0.152625  0.089154          -0.524470     -0.002095 -0.502703   
28030    0.152625  0.186815          -0.110506     -0.002095 -0.326172   
277869   0.251879  0.186815          -0.524470     -0.002095 -0.502703   
773630   0.152625  0.186815           1.342208     -0.002095  1.391478   

        SBA_Appv  MIS_Status  Log_DisbursementGross  Log_GrAppv  Log_SBA_Appv  \
148172 -0.606817           1              -1.064054   -1.008137     -0.933481   
744579 -0.609553           0              -0.991151   -0.938082     -0.940463   
321200 -0.565780           0              -0.945343   -0.893964     -0.834204   
74901   0.112702           1               1.316535    0.442430      0.106791   
426895 -0.543894           0              -0.743325   -0.698569     -0.785029   
...          ...         ...                    ...         ...           ...   
192476 -0.631440           1              -1.010078   -1.032624     -0.998151   
17730  -0.456348           0              -0.743325   -0.698569     -0.609445   
28030  -0.434461           1              -0.117102   -0.394781     -0.569976   
277869 -0.543894           0              -0.743325   -0.698569     -0.785029   
773630  1.272140           0               0.851094    0.871911      0.820722   

        Log_BalanceGross  TotalJobs  IncomeToLoanRatio  EmployeesToLoanRatio  \
148172         -0.002098  -0.063679           1.079313              0.203930   
744579         -0.002098  -0.080758           1.031658              0.095556   
321200         -0.002098  -0.080758           1.080727              0.195567   
74901          -0.002098   0.021717          24.227422          

In [92]:
test_encoded

City     State    Zip      Bank  BankState   NAICS     NoEmp  \
244526  0.169492  0.184227  91360  0.141177   0.178801  621210 -0.045146   
473020  0.241379  0.184227  91326  0.154334   0.217642  238990 -0.071347   
176231  0.141176  0.198565  14203  0.073645   0.168202  541511 -0.123748   
605480  0.089294  0.176561  84066  0.186588   0.167275  532412 -0.136849   
680297  0.174878  0.117244  55110  0.412096   0.380604  511120 -0.123748   
...          ...       ...    ...       ...        ...     ...       ...   
140684  0.221202  0.168644  72106  0.220430   0.130193  484121 -0.123748   
682787  0.412092  0.184227  91306  0.545563   0.217642  611519 -0.136849   
590016  0.153938  0.184227  92124  0.067005   0.217642       0  0.085857   
687978  0.138222  0.188433  76834  0.103226   0.139857       0 -0.097548   
158557  0.136499  0.143158  17112  0.081911   0.076427       0 -0.123748   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
244526  0.170670  -0.035352    -0.045405              1    0.070886   
473020  0.170670  -0.035352    -0.019802              1    0.243731   
176231  0.185603  -0.026808    -0.036871              0    0.243731   
605480  0.170670  -0.035352    -0.041138              1    0.186517   
680297  0.170670  -0.026808    -0.036871              0    0.243731   
...          ...        ...          ...            ...         ...   
140684  0.185603  -0.022535    -0.036871              1    0.186517   
682787  0.185603  -0.035352    -0.041138              0    0.243731   
590016  0.185603  -0.035352    -0.045405          72590    0.070886   
687978  0.170670  -0.035352    -0.045405              1    0.070886   
158557  0.185603  -0.035352    -0.045405              1    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
244526   0.152625  0.186815           3.327185     -0.002095  3.405700   
473020   0.251879  0.186815          -0.559263     -0.002095 -0.538010   
176231   0.251879  0.186815          -0.170323     -0.002095 -0.502703   
605480   0.152625  0.186815          -0.200736     -0.002095  0.026891   
680297   0.152625  0.186815          -0.646247     -0.002095 -0.626275   
...           ...       ...                ...           ...       ...   
140684   0.152625  0.186815          -0.472279     -0.002095 -0.449744   
682787   0.152625  0.186815          -0.663644     -0.002095 -0.643928   
590016   0.152625  0.186815          -0.089549     -0.002095 -0.061375   
687978   0.152625  0.186815           0.853358     -0.002095  0.895425   
158557   0.152625  0.089154          -0.587098     -0.002095 -0.566255   

        SBA_Appv  MIS_Status  Log_DisbursementGross  Log_GrAppv  Log_SBA_Appv  \
244526  2.629607           0               1.464917    1.482899      1.289124   
473020 -0.565780           0              -0.819308   -0.772211     -0.834204   
176231 -0.543894           0              -0.186719   -0.698569     -0.785029   
605480  0.003269           0              -0.224064    0.026535      0.003264   
680297 -0.620496           1              -1.039158   -0.984236     -0.968891   
...          ...         ...                    ...         ...           ...   
140684 -0.511064           1              -0.639188   -0.597372     -0.715523   
682787 -0.616119           1              -1.089586   -1.032624     -0.957423   
590016 -0.078805           1              -0.093816   -0.063339     -0.082084   
687978  0.810882           0               0.616999    0.639443      0.593814   
158557 -0.541267           0              -0.884546   -0.835298     -0.779287   

        Log_BalanceGross  TotalJobs  IncomeToLoanRatio  EmployeesToLoanRatio  \
244526         -0.002098  -0.080758           1.265278             -0.017168   
473020         -0.002098  -0.055155           0.988482              0.126104   
176231         -0.002098  -0.063679           0.313155              0.227523   
605480         -0.002098  -0.076491         -61.401723          

In [93]:
X_train = train_encoded.copy()
X_test = test_encoded.copy()

In [94]:
target_col = 'MIS_Status'
y_train = X_train['MIS_Status']
X_train.drop(columns=[target_col], axis=1, inplace=True)

In [95]:
target_col = 'MIS_Status'
y_test = X_test['MIS_Status']
X_test.drop(columns=[target_col], axis=1, inplace=True)


In [96]:
import lightgbm as lgb

train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1})
test_data = lgb.Dataset(data=X_test, label=y_test, params={"verbose":-1})
lgb_clf = lgb.train(params={"verbose":-1},
                    train_set=train_data)

In [97]:
from sklearn.metrics import roc_auc_score
print("AUC score on Test dataset:", roc_auc_score(y_test, lgb_clf.predict(X_test)))
print("AUC score on Train dataset:", roc_auc_score(y_train, lgb_clf.predict(X_train)))

AUC score on Test dataset: 0.8205511277259651
AUC score on Train dataset: 0.8468756526040521


In [44]:
from optuna.integration import LightGBMPruningCallback
import tqdm as notebook_tqdm
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import optuna
import warnings

warnings.filterwarnings("ignore", category=UserWarning)
study_model_iteractions = {}

def objective(trial, X, y):
    param_grid = {
        #         "device_type": trial.suggest_categorical("device_type", ['gpu']),
        "n_estimators": trial.suggest_categorical("n_estimators", [10000]),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "num_leaves": trial.suggest_int("num_leaves", 20, 3000, step=20),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 200, 10000, step=100),
        "max_bin": trial.suggest_int("max_bin", 200, 300),
        "lambda_l1": trial.suggest_int("lambda_l1", 0, 100, step=5),
        "lambda_l2": trial.suggest_int("lambda_l2", 0, 100, step=5),
        "min_gain_to_split": trial.suggest_float("min_gain_to_split", 0, 15),
        "bagging_fraction": trial.suggest_float(
            "bagging_fraction", 0.2, 0.95, step=0.1
        ),
        "bagging_freq": trial.suggest_categorical("bagging_freq", [1]),
        "feature_fraction": trial.suggest_float(
            "feature_fraction", 0.2, 0.95, step=0.1
        ),
        "metric":"auc"
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=1121218)

    cv_scores = np.empty(5)
    cv_iteractions = np.empty(5)
    for idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):
        X_train, X_valid = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_valid = y.iloc[train_idx], y.iloc[test_idx]

        train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1}, categorical_feature=categorical_columns)
        valid_data = lgb.Dataset(data=X_valid, label=y_valid, params={"verbose":-1}, categorical_feature=categorical_columns)
        lgb_clf = lgb.train(params=param_grid,
                            train_set=train_data,
                            valid_sets=[valid_data],
                            categorical_feature=categorical_columns,
                            callbacks=[LightGBMPruningCallback(trial, "auc"),
                                        lgb.early_stopping(stopping_rounds=5)]  
                            )
        preds = lgb_clf.predict(X_valid)
        cv_scores[idx] = roc_auc_score(y_valid, preds)
        cv_iteractions[idx] = lgb_clf.best_iteration
    
    study_model_iteractions[trial.number] = np.mean(cv_iteractions)

    return np.mean(cv_scores)

In [98]:
from optuna.integration import LightGBMPruningCallback
import tqdm as notebook_tqdm
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import optuna
import warnings

warnings.filterwarnings("ignore", category=UserWarning)
study_model_iteractions = {}

def objective(trial, X, y):
    param_grid = {
        # Refer to the Official guide : https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
        "num_iterations": 10000,
        "num_threads": 16,
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, step=0.05),
        #"num_leaves": trial.suggest_int("num_leaves", 50, 150, step=5),
        "num_leaves": trial.suggest_int("num_leaves", 20, 3000, step=20),
        #"max_depth": trial.suggest_int("max_depth", 5, 20, step=2),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 100, 1000, step=100),
        ##############################
        #'lambda_l1': trial.suggest_float('lambda_l1', 1e-8, 10.0, log=True),
        #'lambda_l2': trial.suggest_float('lambda_l2', 1e-8, 10.0, log=True),
        "lambda_l1": trial.suggest_int("lambda_l1", 0, 100, step=5),
        "lambda_l2": trial.suggest_int("lambda_l2", 0, 100, step=5),
        #"lambda_l1": trial.suggest_float("lambda_l1", 0.01, 0.1, step=0.01),
        #"lambda_l2": trial.suggest_float("lambda_l2", 0.01, 0.1, step=0.01),
        ########################
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.8, 1.0, step=0.1),
        "bagging_freq": trial.suggest_categorical("bagging_freq", [5]),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.8, 1.0, step=0.1),
        #######################
        "is_unbalance": trial.suggest_categorical("is_unbalance",[True, False]),
        ########################
        "verbose": -1,
        "objective":"binary",
        "metric":"auc"
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=1121218)

    cv_scores = np.empty(5)
    cv_iteractions = np.empty(5)
    for idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):
        X_train, X_valid = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_valid = y.iloc[train_idx], y.iloc[test_idx]

        train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1}, categorical_feature=categorical_columns)
        valid_data = lgb.Dataset(data=X_valid, label=y_valid, params={"verbose":-1}, categorical_feature=categorical_columns)
        lgb_clf = lgb.train(params=param_grid,
                            train_set=train_data,
                            valid_sets=[valid_data],
                            categorical_feature=categorical_columns,
                            callbacks=[LightGBMPruningCallback(trial, "auc"),
                                        lgb.early_stopping(stopping_rounds=5)]  
                            )
        preds = lgb_clf.predict(X_valid)
        cv_scores[idx] = roc_auc_score(y_valid, preds)
        cv_iteractions[idx] = lgb_clf.best_iteration
    
    study_model_iteractions[trial.number] = np.mean(cv_iteractions)

    return np.mean(cv_scores)

In [99]:
study = optuna.create_study(direction="maximize", study_name="LGBM Classifier")
func = lambda trial: objective(trial, X_train, y_train)
study.optimize(func, n_trials=200)

[I 2023-12-08 13:48:16,780] A new study created in memory with name: LGBM Classifier


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[121]	valid_0's auc: 0.801413
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[113]	valid_0's auc: 0.800578
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[100]	valid_0's auc: 0.802428
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[117]	valid_0's auc: 0.80037
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[128]	valid_0's auc: 0.801783


[I 2023-12-08 13:48:37,701] Trial 0 finished with value: 0.801314474180532 and parameters: {'learning_rate': 0.26, 'num_leaves': 380, 'max_depth': 11, 'min_data_in_leaf': 200, 'lambda_l1': 25, 'lambda_l2': 75, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': False}. Best is trial 0 with value: 0.801314474180532.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[647]	valid_0's auc: 0.799683
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[587]	valid_0's auc: 0.79893
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[280]	valid_0's auc: 0.797246
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[634]	valid_0's auc: 0.798788
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[485]	valid_0's auc: 0.799062


[I 2023-12-08 13:49:20,974] Trial 1 finished with value: 0.7987416761387767 and parameters: {'learning_rate': 0.26, 'num_leaves': 760, 'max_depth': 3, 'min_data_in_leaf': 600, 'lambda_l1': 20, 'lambda_l2': 15, 'bagging_fraction': 0.9, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': False}. Best is trial 0 with value: 0.801314474180532.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[176]	valid_0's auc: 0.799028
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[136]	valid_0's auc: 0.798746
Training until validation scores don't improve for 5 rounds


[W 2023-12-08 13:49:30,152] Trial 2 failed with parameters: {'learning_rate': 0.26, 'num_leaves': 1220, 'max_depth': 9, 'min_data_in_leaf': 600, 'lambda_l1': 65, 'lambda_l2': 5, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': False} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "d:\Work\Gre\UTD\Courses\Fall\MIS6341\Softwares\Python\ml-fall-2023\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\Asus\AppData\Local\Temp\ipykernel_25088\2029209496.py", line 2, in <lambda>
    func = lambda trial: objective(trial, X_train, y_train)
  File "C:\Users\Asus\AppData\Local\Temp\ipykernel_25088\3360629302.py", line 51, in objective
    lgb_clf = lgb.train(params=param_grid,
  File "d:\Work\Gre\UTD\Courses\Fall\MIS6341\Softwares\Python\ml-fall-2023\lib\site-packages\lightgbm\engine.py", line 266, in train
    booster.update(fobj=fobj)
  File "d

KeyboardInterrupt: 

In [58]:
print(f"\tBest value (AUC): {study.best_value:.5f}")
print(f"\tBest params:")

for key, value in study.best_params.items():
    print(f"\t\t{key}: {value}")

print("Best model best_iteration:", study_model_iteractions[study.best_trial.number])

	Best value (AUC): 0.75404
	Best params:
		learning_rate: 0.16000000000000003
		num_leaves: 2320
		max_depth: 4
		min_data_in_leaf: 100
		lambda_l1: 5
		lambda_l2: 50
		bagging_fraction: 0.8
		bagging_freq: 5
		feature_fraction: 0.8
		is_unbalance: True
Best model best_iteration: 22.2


In [59]:
best_params = {"verbose": -1,
                "objective":"binary",
                "metric":"auc"
            }
for key,val in study.best_params.items():
    best_params[key] = val

best_params["num_iterations"] = int(study_model_iteractions[study.best_trial.number])
print(best_params)

{'verbose': -1, 'objective': 'binary', 'metric': 'auc', 'learning_rate': 0.16000000000000003, 'num_leaves': 2320, 'max_depth': 4, 'min_data_in_leaf': 100, 'lambda_l1': 5, 'lambda_l2': 50, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 0.8, 'is_unbalance': True, 'num_iterations': 22}


# Training the model with parameters found using Optuna

In [60]:

train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1})
test_data = lgb.Dataset(data=X_test, label=y_test, params={"verbose":-1})
best_lgb = lgb.train(params=best_params,
                    train_set=train_data) 

In [61]:
print("AUC score on Test dataset:", roc_auc_score(y_test, best_lgb.predict(X_test)))
print("AUC score on Train dataset:", roc_auc_score(y_train, best_lgb.predict(X_train)))

AUC score on Test dataset: 0.7941855023542295
AUC score on Train dataset: 0.8168939523486363


# Optuna LightGBM Tuner

In [62]:
import optuna.integration.lightgbm as lgb_optuna

train_data = lgb_optuna.Dataset(data=X_train, label=y_train, params={"verbose":-1})
test_data = lgb_optuna.Dataset(data=X_test, label=y_test, params={"verbose":-1})

In [69]:
from lightgbm import early_stopping
from lightgbm import log_evaluation

params = {
        #         "device_type": trial.suggest_categorical("device_type", ['gpu']),
        "n_estimators": 1000,
        #"learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        #"num_leaves": trial.suggest_int("num_leaves", 20, 3000, step=20),
        "max_depth": 12,
        #"min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 200, 10000, step=100),
        #"max_bin": trial.suggest_int("max_bin", 200, 300),
        #"lambda_l1": trial.suggest_int("lambda_l1", 0, 100, step=5),
        #"lambda_l2": trial.suggest_int("lambda_l2", 0, 100, step=5),
        #"min_gain_to_split": trial.suggest_float("min_gain_to_split", 0, 15),
        #"bagging_fraction": trial.suggest_float(
         #   "bagging_fraction", 0.2, 0.95, step=0.1
        #),
        #"bagging_freq": trial.suggest_categorical("bagging_freq", [1]),
        #"feature_fraction": trial.suggest_float(
         #   "feature_fraction", 0.2, 0.95, step=0.1
        #),
        "metric":"auc"
    }


model = lgb_optuna.train(params,
                        train_data,
                        valid_sets=[test_data],
                        callbacks=[early_stopping(stopping_rounds=5), log_evaluation(100)]
)

[I 2023-12-08 13:09:25,895] A new study created in memory with name: no-name-408e7fdb-ff88-47cc-9837-a251230c035a










[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022615 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820921










[I 2023-12-08 13:09:30,809] Trial 0 finished with value: 0.8213857348065972 and parameters: {'feature_fraction': 1.0}. Best is trial 0 with value: 0.8213857348065972.






Early stopping, best iteration is:
[110]	valid_0's auc: 0.821386
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.063154 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820974
[200]	valid_0's auc: 0.825087










[I 2023-12-08 13:09:40,557] Trial 1 finished with value: 0.8274361264266092 and parameters: {'feature_fraction': 0.5}. Best is trial 1 with value: 0.8274361264266092.






Early stopping, best iteration is:
[277]	valid_0's auc: 0.827436
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.049758 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:09:41,795] Trial 2 finished with value: 0.7995953511467344 and parameters: {'feature_fraction': 0.8999999999999999}. Best is trial 1 with value: 0.8274361264266092.






Early stopping, best iteration is:
[10]	valid_0's auc: 0.799595
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.047940 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.821073
[200]	valid_0's auc: 0.825099
Early stopping, best iteration is:
[201]	valid_0's auc: 0.825179










[I 2023-12-08 13:09:49,041] Trial 3 finished with value: 0.8251794860809585 and parameters: {'feature_fraction': 0.7}. Best is trial 1 with value: 0.8274361264266092.






[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.044699 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:09:50,266] Trial 4 finished with value: 0.7997713717796255 and parameters: {'feature_fraction': 0.8}. Best is trial 1 with value: 0.8274361264266092.






Early stopping, best iteration is:
[11]	valid_0's auc: 0.799771
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.048231 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.821081
[200]	valid_0's auc: 0.825072










[I 2023-12-08 13:09:58,615] Trial 5 finished with value: 0.8259575658217385 and parameters: {'feature_fraction': 0.4}. Best is trial 1 with value: 0.8274361264266092.






Early stopping, best iteration is:
[226]	valid_0's auc: 0.825958
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.046014 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:02,873] Trial 6 finished with value: 0.8210950776356571 and parameters: {'feature_fraction': 0.6}. Best is trial 1 with value: 0.8274361264266092.
feature_fraction, val_score: 0.827436: 100%|##########| 7/7 [00:36<00:00,  5.28s/it]


[100]	valid_0's auc: 0.821001
Early stopping, best iteration is:
[98]	valid_0's auc: 0.821095


[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023050 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:07,836] Trial 7 finished with value: 0.826154516021373 and parameters: {'num_leaves': 2419}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.020994 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds


Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155


num_leaves, val_score: 0.827436:   5%|5         | 1/20 [00:10<01:33,  4.93s/it]



[I 2023-12-08 13:10:13,626] Trial 8 finished with value: 0.826154516021373 and parameters: {'num_leaves': 3576}. Best is trial 7 with value: 0.826154516021373.






[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.064147 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:18,688] Trial 9 finished with value: 0.8260331580080544 and parameters: {'num_leaves': 1749}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826033
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022373 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:19,819] Trial 10 finished with value: 0.7532242311729355 and parameters: {'num_leaves': 2}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[15]	valid_0's auc: 0.753224
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.058129 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:25,365] Trial 11 finished with value: 0.826154516021373 and parameters: {'num_leaves': 2747}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.054766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:30,110] Trial 12 finished with value: 0.8260584459368836 and parameters: {'num_leaves': 1579}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826058
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.054554 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds


Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155


[I 2023-12-08 13:10:35,747] Trial 13 finished with value: 0.826154516021373 and parameters: {'num_leaves': 3935}. Best is trial 7 with value: 0.826154516021373.






[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.064417 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:38,990] Trial 14 finished with value: 0.8245861846708887 and parameters: {'num_leaves': 751}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.824586
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022816 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:44,359] Trial 15 finished with value: 0.826154516021373 and parameters: {'num_leaves': 2739}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.060495 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:49,090] Trial 16 finished with value: 0.826154516021373 and parameters: {'num_leaves': 2730}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.065495 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:53,028] Trial 17 finished with value: 0.8259005730356284 and parameters: {'num_leaves': 1039}. Best is trial 7 with value: 0.826154516021373.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.825901
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.059193 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:10:58,305] Trial 18 finished with value: 0.8261577786978079 and parameters: {'num_leaves': 2244}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826158
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.048556 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:03,612] Trial 19 finished with value: 0.826154516021373 and parameters: {'num_leaves': 3417}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.053998 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:08,687] Trial 20 finished with value: 0.826122695671121 and parameters: {'num_leaves': 2059}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826123
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.064398 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:13,916] Trial 21 finished with value: 0.8261415121597745 and parameters: {'num_leaves': 2288}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826142
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.052775 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:17,734] Trial 22 finished with value: 0.8261478213227412 and parameters: {'num_leaves': 1158}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826148
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023199 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:24,029] Trial 23 finished with value: 0.826154516021373 and parameters: {'num_leaves': 2369}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.072505 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds


Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155






[I 2023-12-08 13:11:31,099] Trial 24 finished with value: 0.826154516021373 and parameters: {'num_leaves': 3218}. Best is trial 18 with value: 0.8261577786978079.






[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.076505 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:36,228] Trial 25 finished with value: 0.8261290547931841 and parameters: {'num_leaves': 1497}. Best is trial 18 with value: 0.8261577786978079.






Early stopping, best iteration is:
[18]	valid_0's auc: 0.826129
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028023 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds










[I 2023-12-08 13:11:41,812] Trial 26 finished with value: 0.826154516021373 and parameters: {'num_leaves': 2900}. Best is trial 18 with value: 0.8261577786978079.
num_leaves, val_score: 0.827436: 100%|##########| 20/20 [01:38<00:00,  4.95s/it]


Early stopping, best iteration is:
[18]	valid_0's auc: 0.826155


[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.056824 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820875
[200]	valid_0's auc: 0.824943










[I 2023-12-08 13:11:51,784] Trial 27 finished with value: 0.826956385996343 and parameters: {'bagging_fraction': 0.70482021406053, 'bagging_freq': 3}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[259]	valid_0's auc: 0.826956
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024686 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820218
[200]	valid_0's auc: 0.825129










[I 2023-12-08 13:12:01,300] Trial 28 finished with value: 0.8257818768118185 and parameters: {'bagging_fraction': 0.7228587255123846, 'bagging_freq': 3}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[222]	valid_0's auc: 0.825782
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019742 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.819439










[I 2023-12-08 13:12:08,877] Trial 29 finished with value: 0.8233527448983227 and parameters: {'bagging_fraction': 0.4898071500761211, 'bagging_freq': 2}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[169]	valid_0's auc: 0.823353
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.063478 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820734










[I 2023-12-08 13:12:16,679] Trial 30 finished with value: 0.8236275070495939 and parameters: {'bagging_fraction': 0.9553434358737323, 'bagging_freq': 7}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[145]	valid_0's auc: 0.823628
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.031758 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820529










[I 2023-12-08 13:12:24,084] Trial 31 finished with value: 0.8229729314067716 and parameters: {'bagging_fraction': 0.6821013950473284, 'bagging_freq': 5}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[131]	valid_0's auc: 0.822973
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.066995 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820491










[I 2023-12-08 13:12:32,401] Trial 32 finished with value: 0.8237445884085096 and parameters: {'bagging_fraction': 0.6998539549141892, 'bagging_freq': 1}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[169]	valid_0's auc: 0.823745
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.034312 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.819528
[200]	valid_0's auc: 0.824228










[I 2023-12-08 13:12:43,756] Trial 33 finished with value: 0.82537301294433 and parameters: {'bagging_fraction': 0.43368617708217166, 'bagging_freq': 5}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[240]	valid_0's auc: 0.825373
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027434 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820902










[I 2023-12-08 13:12:53,048] Trial 34 finished with value: 0.8246126889899005 and parameters: {'bagging_fraction': 0.9150523776507908, 'bagging_freq': 4}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[158]	valid_0's auc: 0.824613
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062956 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820615










[I 2023-12-08 13:13:01,498] Trial 35 finished with value: 0.8235324407595638 and parameters: {'bagging_fraction': 0.8170913743603612, 'bagging_freq': 7}. Best is trial 27 with value: 0.826956385996343.






Early stopping, best iteration is:
[153]	valid_0's auc: 0.823532
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022388 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:13:15,460] Trial 36 finished with value: 0.8277031534241576 and parameters: {'bagging_fraction': 0.5638971041664391, 'bagging_freq': 1}. Best is trial 36 with value: 0.8277031534241576.
bagging, val_score: 0.827703: 100%|##########| 10/10 [01:33<00:00,  9.36s/it]


Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703


[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024909 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:13:30,350] Trial 37 finished with value: 0.8277031534241576 and parameters: {'feature_fraction': 0.516}. Best is trial 37 with value: 0.8277031534241576.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.057045 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820209
[200]	valid_0's auc: 0.824595










[I 2023-12-08 13:13:40,293] Trial 38 finished with value: 0.8250771914165288 and parameters: {'feature_fraction': 0.5479999999999999}. Best is trial 37 with value: 0.8277031534241576.






Early stopping, best iteration is:
[212]	valid_0's auc: 0.825077
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028756 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820957










[I 2023-12-08 13:13:47,982] Trial 39 finished with value: 0.8242539407453727 and parameters: {'feature_fraction': 0.45199999999999996}. Best is trial 37 with value: 0.8277031534241576.






Early stopping, best iteration is:
[169]	valid_0's auc: 0.824254
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022185 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820617
[200]	valid_0's auc: 0.82471










[I 2023-12-08 13:13:59,031] Trial 40 finished with value: 0.8262509119781463 and parameters: {'feature_fraction': 0.58}. Best is trial 37 with value: 0.8277031534241576.






Early stopping, best iteration is:
[250]	valid_0's auc: 0.826251
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.060014 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:14:13,622] Trial 41 finished with value: 0.8277031534241576 and parameters: {'feature_fraction': 0.484}. Best is trial 37 with value: 0.8277031534241576.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.064628 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.821113










[I 2023-12-08 13:14:19,505] Trial 42 finished with value: 0.8230762850363174 and parameters: {'feature_fraction': 0.42}. Best is trial 37 with value: 0.8277031534241576.
feature_fraction_stage2, val_score: 0.827703: 100%|##########| 6/6 [01:04<00:00, 10.67s/it]


Early stopping, best iteration is:
[128]	valid_0's auc: 0.823076


[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.053567 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824616










[I 2023-12-08 13:14:28,880] Trial 43 finished with value: 0.8258954615132074 and parameters: {'lambda_l1': 0.00043836656325946103, 'lambda_l2': 0.00047688564686361603}. Best is trial 43 with value: 0.8258954615132074.






Early stopping, best iteration is:
[243]	valid_0's auc: 0.825895
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021066 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820259
[200]	valid_0's auc: 0.825007
[300]	valid_0's auc: 0.827409
[400]	valid_0's auc: 0.828675
[500]	valid_0's auc: 0.829888










[I 2023-12-08 13:14:48,038] Trial 44 finished with value: 0.8299583107514025 and parameters: {'lambda_l1': 1.1298901291575557e-08, 'lambda_l2': 8.587835379337236}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[502]	valid_0's auc: 0.829958
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.029912 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820679
[200]	valid_0's auc: 0.82491
[300]	valid_0's auc: 0.827209










[I 2023-12-08 13:15:01,199] Trial 45 finished with value: 0.8273377798486642 and parameters: {'lambda_l1': 3.67767695921121e-08, 'lambda_l2': 7.523465984341601}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[304]	valid_0's auc: 0.827338
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022771 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820826
[200]	valid_0's auc: 0.825224










[I 2023-12-08 13:15:13,248] Trial 46 finished with value: 0.8271408052685114 and parameters: {'lambda_l1': 1.1308798638098176e-08, 'lambda_l2': 4.713138355418288}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[287]	valid_0's auc: 0.827141
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.050627 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820807
[200]	valid_0's auc: 0.825599










[I 2023-12-08 13:15:23,679] Trial 47 finished with value: 0.826543179700965 and parameters: {'lambda_l1': 7.855601210349932, 'lambda_l2': 5.1461856809573095e-08}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[234]	valid_0's auc: 0.826543
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025926 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824616










[I 2023-12-08 13:15:34,316] Trial 48 finished with value: 0.8258952023728582 and parameters: {'lambda_l1': 4.621555853614326e-06, 'lambda_l2': 0.0230350262970697}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[243]	valid_0's auc: 0.825895
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.046876 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824616










[I 2023-12-08 13:15:44,085] Trial 49 finished with value: 0.8258952048887839 and parameters: {'lambda_l1': 1.9717376551170918e-05, 'lambda_l2': 0.022680695625209}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[243]	valid_0's auc: 0.825895
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023672 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:15:58,219] Trial 50 finished with value: 0.8277031535439635 and parameters: {'lambda_l1': 1.1288974193004864e-08, 'lambda_l2': 9.111665229611795e-07}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025029 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:16:11,563] Trial 51 finished with value: 0.8277031534241576 and parameters: {'lambda_l1': 1.519436282003942e-08, 'lambda_l2': 4.484706134417923e-07}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.049076 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:16:23,979] Trial 52 finished with value: 0.8277031534241576 and parameters: {'lambda_l1': 1.0637323686945633e-08, 'lambda_l2': 5.004985180648629e-07}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.046792 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:16:36,072] Trial 53 finished with value: 0.8277031529449336 and parameters: {'lambda_l1': 1.6061545353426933e-07, 'lambda_l2': 1.8037597327713072e-06}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.045186 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:16:48,443] Trial 54 finished with value: 0.8277031528251276 and parameters: {'lambda_l1': 3.65027529352504e-07, 'lambda_l2': 3.2813787636570894e-06}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.063889 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:17:02,119] Trial 55 finished with value: 0.8277031534241576 and parameters: {'lambda_l1': 1.4979168706790313e-08, 'lambda_l2': 1.1491821703096699e-08}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024017 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:17:15,930] Trial 56 finished with value: 0.8277031537835755 and parameters: {'lambda_l1': 4.827199242139198e-07, 'lambda_l2': 3.5890347643707147e-05}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019773 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:17:28,124] Trial 57 finished with value: 0.8277031541429934 and parameters: {'lambda_l1': 6.806241654915263e-07, 'lambda_l2': 3.836429425552569e-05}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022909 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:17:41,353] Trial 58 finished with value: 0.8277031528251276 and parameters: {'lambda_l1': 6.787429668677014e-07, 'lambda_l2': 0.00011379339169931773}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.029883 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:17:54,071] Trial 59 finished with value: 0.8277031540231875 and parameters: {'lambda_l1': 3.250226709354578e-07, 'lambda_l2': 3.418840975515011e-05}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023513 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:18:07,013] Trial 60 finished with value: 0.8277031535439635 and parameters: {'lambda_l1': 2.981061723418087e-07, 'lambda_l2': 2.8291012153047283e-05}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.052339 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:18:19,370] Trial 61 finished with value: 0.8277031522260977 and parameters: {'lambda_l1': 4.851677275919252e-07, 'lambda_l2': 1.6427007766731608e-05}. Best is trial 44 with value: 0.8299583107514025.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062276 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.82101
[200]	valid_0's auc: 0.824619
[300]	valid_0's auc: 0.827185










[I 2023-12-08 13:18:32,543] Trial 62 finished with value: 0.8277031530647396 and parameters: {'lambda_l1': 1.57808497162591e-07, 'lambda_l2': 2.6237773170124403e-05}. Best is trial 44 with value: 0.8299583107514025.
regularization_factors, val_score: 0.829958: 100%|##########| 20/20 [04:13<00:00, 12.65s/it]


Early stopping, best iteration is:
[332]	valid_0's auc: 0.827703


[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023852 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820695
[200]	valid_0's auc: 0.82511
[300]	valid_0's auc: 0.827392
[400]	valid_0's auc: 0.828844










[I 2023-12-08 13:18:50,545] Trial 63 finished with value: 0.8298394370350233 and parameters: {'min_child_samples': 25}. Best is trial 63 with value: 0.8298394370350233.






[500]	valid_0's auc: 0.829839
Early stopping, best iteration is:
[495]	valid_0's auc: 0.829839
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.057353 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820232
[200]	valid_0's auc: 0.824652
[300]	valid_0's auc: 0.827378










[I 2023-12-08 13:19:03,291] Trial 64 finished with value: 0.8283711866338499 and parameters: {'min_child_samples': 10}. Best is trial 63 with value: 0.8298394370350233.






Early stopping, best iteration is:
[369]	valid_0's auc: 0.828371
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820917
[200]	valid_0's auc: 0.825138
[300]	valid_0's auc: 0.82743










[I 2023-12-08 13:19:15,469] Trial 65 finished with value: 0.8279734622071955 and parameters: {'min_child_samples': 50}. Best is trial 63 with value: 0.8298394370350233.






Early stopping, best iteration is:
[332]	valid_0's auc: 0.827973
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.057658 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.820253
[200]	valid_0's auc: 0.824652
[300]	valid_0's auc: 0.826997
[400]	valid_0's auc: 0.828138










[I 2023-12-08 13:19:31,634] Trial 66 finished with value: 0.8290972687194248 and parameters: {'min_child_samples': 5}. Best is trial 63 with value: 0.8298394370350233.






Early stopping, best iteration is:
[484]	valid_0's auc: 0.829097
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021462 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4737
[LightGBM] [Info] Number of data points in the train set: 560178, number of used features: 28
Training until validation scores don't improve for 5 rounds
[100]	valid_0's auc: 0.821478










[I 2023-12-08 13:19:36,349] Trial 67 finished with value: 0.8217209293139527 and parameters: {'min_child_samples': 100}. Best is trial 63 with value: 0.8298394370350233.
min_data_in_leaf, val_score: 0.829958: 100%|##########| 5/5 [01:03<00:00, 12.76s/it]

Early stopping, best iteration is:
[104]	valid_0's auc: 0.821721


In [70]:
best_params = model.params
print("AUC score on Test dataset:", roc_auc_score(y_test, model.predict(X_test, num_iteration=model.best_iteration)))
print("  Best Model Params: ")
for key, value in best_params.items():
    print("    {}: {}".format(key, value))
print("Model Best Iteration:", model.best_iteration)

AUC score on Test dataset: 0.8299583107514024
  Best Model Params: 
    max_depth: 12
    metric: auc
    feature_pre_filter: False
    lambda_l1: 1.1298901291575557e-08
    lambda_l2: 8.587835379337236
    num_leaves: 31
    feature_fraction: 0.5
    bagging_fraction: 0.5638971041664391
    bagging_freq: 1
    min_child_samples: 20
    objective: None
    num_iterations: 1000
Model Best Iteration: 502
