In [129]:
import pandas as pd
pd.set_option('display.max_columns', 1500)

import warnings
warnings.filterwarnings('ignore')

#Extend cell width
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

In [130]:
df = pd.read_csv("D:/Work/Gre/UTD/Courses/Fall/MIS6341/Softwares/Python/ml-fall-2023/Project2/SBA_loans_project_2.csv")
df.drop(columns="index",inplace=True)

In [131]:
df

City State    Zip                            Bank  \
0              NEW YORK    NY  10003  JPMORGAN CHASE BANK NATL ASSOC   
1             PAWTUCKET    RI   2860        CITIZENS BANK NATL ASSOC   
2              ISSAQUAH    WA  98027       FIRST-CITIZENS BK & TR CO   
3                 HURST    TX  76053                   WILSHIRE BANK   
4                ALPINE    CA  91901         CALIFORNIA BANK & TRUST   
...                 ...   ...    ...                             ...   
800250          Kenmore    NY  14217    KEYBANK NATIONAL ASSOCIATION   
800251  MENOMONEE FALLS    WI  53051             WAUKESHA STATE BANK   
800252         LONGVIEW    TX  75604          CAPITAL ONE NATL ASSOC   
800253           CAMDEN    NJ   8105      BANK OF AMERICA NATL ASSOC   
800254         COVENTRY    RI   2816        CITIZENS BANK NATL ASSOC   

       BankState   NAICS  NoEmp  NewExist  CreateJob  RetainedJob  \
0             IL  561439      9       1.0          1            9   
1             RI  541810      8       1.0          4           12   
2             WA  448210      9       2.0          0            0   
3             CA  722213      4       1.0          0            4   
4             CA  233210      1       1.0          0            1   
...          ...     ...    ...       ...        ...          ...   
800250        OH  561720    112       1.0          0            0   
800251        WI  337110     75       1.0          0           75   
800252        VA  517310      2       1.0          0            0   
800253        RI  447110      4       2.0          0            0   
800254        RI  541511      1       1.0          0            1   

        FranchiseCode  UrbanRural RevLineCr LowDoc  DisbursementGross  \
0                   1           1         0      N            68000.0   
1                   0           1         N      N            90000.0   
2                   1           0         N      N           450000.0   
3                   1           1         0      N           140000.0   
4                   1           2         Y      N            50000.0   
...               ...         ...       ...    ...                ...   
800250              1           1         N      N            45500.0   
800251              1           1         0      N           550000.0   
800252              1           1         0      Y           128800.0   
800253              1           1         Y      N           100000.0   
800254              0           1         N      N            10000.0   

        BalanceGross    GrAppv  SBA_Appv  MIS_Status  
0                0.0   68000.0   34000.0           0  
1                0.0   90000.0   45000.0           1  
2                0.0  450000.0  337500.0           0  
3                0.0  165000.0   82500.0           0  
4                0.0   50000.0   25000.0           0  
...              ...       ...       ...         ...  
800250           0.0   45500.0   22750.0           0  
800251           0.0  550000.0  412500.0           0  
800252           0.0  135000.0  114750.0           0  
800253           0.0  100000.0   50000.0           0  
800254           0.0   10000.0    5000.0           0  

[800255 rows x 19 columns]

In [132]:
df.isnull().sum()

City                   26
State                  13
Zip                     0
Bank                 1381
BankState            1386
NAICS                   0
NoEmp                   0
NewExist              127
CreateJob               0
RetainedJob             0
FranchiseCode           0
UrbanRural              0
RevLineCr            4016
LowDoc               2316
DisbursementGross       0
BalanceGross            0
GrAppv                  0
SBA_Appv                0
MIS_Status              0
dtype: int64

In [133]:
#show unique values in each column and its data type
for col in df.columns:
    print(f'{col} unique values are {df[col].unique()}')
    print("\n")
    print(f'{col} data type is {df[col].dtype}')

City unique values are ['NEW YORK' 'PAWTUCKET' 'ISSAQUAH' ... 'ST  FRANCIS' 'Stevens point'
 'Pylesville']


City data type is object
State unique values are ['NY' 'RI' 'WA' 'TX' 'CA' 'NC' 'MN' 'MO' 'FL' 'IA' 'IL' 'DC' 'PA' 'AL'
 'MS' 'OH' 'MA' 'NJ' 'ME' 'NV' 'LA' 'MI' 'IN' 'GA' 'UT' 'VA' 'WI' 'TN'
 'KS' 'NH' 'CO' 'CT' 'KY' 'AZ' 'ID' 'DE' 'SD' 'AR' 'MD' 'OK' 'SC' 'NM'
 'MT' 'NE' 'OR' 'WY' 'AK' 'HI' 'VT' 'ND' 'WV' nan]


State data type is object
Zip unique values are [10003  2860 98027 ... 78944 17814 95812]


Zip data type is int64
Bank unique values are ['JPMORGAN CHASE BANK NATL ASSOC' 'CITIZENS BANK NATL ASSOC'
 'FIRST-CITIZENS BK & TR CO' ... 'TULSA NATIONAL BANCSHARES, INC'
 'BEACH PLAZA LLC' 'THE LEADERS BANK']


Bank data type is object
BankState unique values are ['IL' 'RI' 'WA' 'CA' 'NC' 'MN' 'MO' 'OR' 'FL' 'IA' 'SD' 'DC' 'TX' 'PA'
 'VA' 'AL' 'OH' 'MS' 'IN' 'MA' 'ME' 'MI' 'DE' 'UT' 'SC' 'NY' 'KS' 'CO'
 'LA' 'WI' 'CT' 'AZ' 'AR' 'MD' 'OK' 'NM' 'ID' 'MT' 'NJ' 'KY' 'NE' 'WY'
 'GA

In [134]:
df

City State    Zip                            Bank  \
0              NEW YORK    NY  10003  JPMORGAN CHASE BANK NATL ASSOC   
1             PAWTUCKET    RI   2860        CITIZENS BANK NATL ASSOC   
2              ISSAQUAH    WA  98027       FIRST-CITIZENS BK & TR CO   
3                 HURST    TX  76053                   WILSHIRE BANK   
4                ALPINE    CA  91901         CALIFORNIA BANK & TRUST   
...                 ...   ...    ...                             ...   
800250          Kenmore    NY  14217    KEYBANK NATIONAL ASSOCIATION   
800251  MENOMONEE FALLS    WI  53051             WAUKESHA STATE BANK   
800252         LONGVIEW    TX  75604          CAPITAL ONE NATL ASSOC   
800253           CAMDEN    NJ   8105      BANK OF AMERICA NATL ASSOC   
800254         COVENTRY    RI   2816        CITIZENS BANK NATL ASSOC   

       BankState   NAICS  NoEmp  NewExist  CreateJob  RetainedJob  \
0             IL  561439      9       1.0          1            9   
1             RI  541810      8       1.0          4           12   
2             WA  448210      9       2.0          0            0   
3             CA  722213      4       1.0          0            4   
4             CA  233210      1       1.0          0            1   
...          ...     ...    ...       ...        ...          ...   
800250        OH  561720    112       1.0          0            0   
800251        WI  337110     75       1.0          0           75   
800252        VA  517310      2       1.0          0            0   
800253        RI  447110      4       2.0          0            0   
800254        RI  541511      1       1.0          0            1   

        FranchiseCode  UrbanRural RevLineCr LowDoc  DisbursementGross  \
0                   1           1         0      N            68000.0   
1                   0           1         N      N            90000.0   
2                   1           0         N      N           450000.0   
3                   1           1         0      N           140000.0   
4                   1           2         Y      N            50000.0   
...               ...         ...       ...    ...                ...   
800250              1           1         N      N            45500.0   
800251              1           1         0      N           550000.0   
800252              1           1         0      Y           128800.0   
800253              1           1         Y      N           100000.0   
800254              0           1         N      N            10000.0   

        BalanceGross    GrAppv  SBA_Appv  MIS_Status  
0                0.0   68000.0   34000.0           0  
1                0.0   90000.0   45000.0           1  
2                0.0  450000.0  337500.0           0  
3                0.0  165000.0   82500.0           0  
4                0.0   50000.0   25000.0           0  
...              ...       ...       ...         ...  
800250           0.0   45500.0   22750.0           0  
800251           0.0  550000.0  412500.0           0  
800252           0.0  135000.0  114750.0           0  
800253           0.0  100000.0   50000.0           0  
800254           0.0   10000.0    5000.0           0  

[800255 rows x 19 columns]

In [135]:
for i in df['RevLineCr']:
    if i not in ['Y','N']:
        df['RevLineCr'].replace(i,'N',inplace=True)
print("RevLineCr",df['RevLineCr'].unique())

for i in df['LowDoc']:
    if i not in ['Y','N']:
        df['LowDoc'].replace(i,'N',inplace=True)
print("LowDoc",df['LowDoc'].unique())

for i in df['NewExist']:
    if i not in [1,2]:
        df['NewExist'].replace(i,None,inplace=True)
print("NewExist",df['NewExist'].unique())

RevLineCr ['N' 'Y']
LowDoc ['N' 'Y']
NewExist [1.0 2.0 None]


In [136]:
df.isnull().sum()

City                   26
State                  13
Zip                     0
Bank                 1381
BankState            1386
NAICS                   0
NoEmp                   0
NewExist             1057
CreateJob               0
RetainedJob             0
FranchiseCode           0
UrbanRural              0
RevLineCr               0
LowDoc                  0
DisbursementGross       0
BalanceGross            0
GrAppv                  0
SBA_Appv                0
MIS_Status              0
dtype: int64

In [137]:
category_cols=['City', 'State', 'Bank', 'BankState', 'RevLineCr', 'LowDoc','NewExist']
for column in category_cols:
  df[column]=df[column].fillna(df[column].mode()[0])

In [138]:
df.isnull().sum()

City                 0
State                0
Zip                  0
Bank                 0
BankState            0
NAICS                0
NoEmp                0
NewExist             0
CreateJob            0
RetainedJob          0
FranchiseCode        0
UrbanRural           0
RevLineCr            0
LowDoc               0
DisbursementGross    0
BalanceGross         0
GrAppv               0
SBA_Appv             0
MIS_Status           0
dtype: int64

In [139]:
from sklearn.model_selection import train_test_split

X_train,X_test = train_test_split(df,test_size=0.3,random_state=123)
X_train.shape, X_test.shape

((560178, 19), (240077, 19))

``` Training set has 560178 rows and testing set has 240077 samples

Target encoding is a data preprocessing technique used to convert categorical variables into numerical values that can be used by machine learning algorithms. It works by replacing each category with the average value of the target variable for that category. This can be helpful for algorithms that cannot handle categorical variables directly.

In this case the target variable is "MIS_Status"```

In [140]:
# Target encoder
import category_encoders as ce
categorical_columns = ['City', 'State', 'Bank', 'BankState', 'RevLineCr', 'LowDoc','NewExist', 'UrbanRural']

encoder = ce.TargetEncoder(cols=categorical_columns)
encoder.fit(X_train, X_train['MIS_Status'])

train_encoded = encoder.transform(X_train)
test_encoded = encoder.transform(X_test)

# Renaming the columns
train_encoded.rename(columns={col: col + "_trg" if col in categorical_columns else col for col in train_encoded.columns}, inplace=False)
test_encoded.rename(columns={col: col + "_trg" if col in categorical_columns else col for col in test_encoded.columns}, inplace=False)

train_encoded.head()

City     State    Zip      Bank  BankState   NAICS  NoEmp  \
148172  0.215946  0.165802  45648  0.740692   0.217642  452990      2   
744579  0.226933  0.165802  43240  0.133135   0.158188  445310      7   
321200  0.252778  0.196143  21037  0.194430   0.076619       0      3   
74901   0.275938  0.184227  90071  0.141177   0.178801  541310     12   
426895  0.057056  0.184227  95037  0.412096   0.380604  561720      1   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
148172   0.17067          2            2              0    0.186517   
744579   0.17067          0            0              0    0.243731   
321200   0.17067          0            0              1    0.070886   
74901    0.17067         12           12              1    0.243731   
426895   0.17067          0            1              0    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
148172   0.152625  0.186815            12500.0           0.0   12500.0   
744579   0.152625  0.186815            20000.0           0.0   20000.0   
321200   0.152625  0.089154            25000.0           0.0   25000.0   
74901    0.251879  0.186815           985500.0           0.0  350000.0   
426895   0.152625  0.186815            50000.0           0.0   50000.0   

        SBA_Appv  MIS_Status  
148172   10625.0           1  
744579   10000.0           0  
321200   20000.0           0  
74901   175000.0           1  
426895   25000.0           0

StandardScaler in scikit-learn is a preprocessing technique that centers and scales numerical features such that they have a mean of zero and a standard deviation of one.

We will make use of the StandardScaler, which is used to transform both the training and test data in the same way, ensuring that the features have the same mean and standard deviation in both datasets.

Here we will scale it on the training set and transform on both training and testing

In [141]:
from sklearn.preprocessing import StandardScaler
from copy import deepcopy

numerical_columns = [ 'NoEmp', 'CreateJob', 'RetainedJob', 'GrAppv', 'SBA_Appv', 'DisbursementGross', 'BalanceGross']
scaler = StandardScaler()
train_encoded[numerical_columns] = scaler.fit_transform(train_encoded[numerical_columns])
test_encoded[numerical_columns] = scaler.transform(test_encoded[numerical_columns])

train_encoded.head()


City     State    Zip      Bank  BankState   NAICS     NoEmp  \
148172  0.215946  0.165802  45648  0.740692   0.217642  452990 -0.123748   
744579  0.226933  0.165802  43240  0.133135   0.158188  445310 -0.058247   
321200  0.252778  0.196143  21037  0.194430   0.076619       0 -0.110648   
74901   0.275938  0.184227  90071  0.141177   0.178801  541310  0.007255   
426895  0.057056  0.184227  95037  0.412096   0.380604  561720 -0.136849   

        NewExist  CreateJob  RetainedJob  FranchiseCode  UrbanRural  \
148172   0.17067  -0.026808    -0.036871              0    0.186517   
744579   0.17067  -0.035352    -0.045405              0    0.243731   
321200   0.17067  -0.035352    -0.045405              1    0.070886   
74901    0.17067   0.015917     0.005801              1    0.243731   
426895   0.17067  -0.035352    -0.041138              0    0.243731   

        RevLineCr    LowDoc  DisbursementGross  BalanceGross    GrAppv  \
148172   0.152625  0.186815          -0.654946     -0.002095 -0.635102   
744579   0.152625  0.186815          -0.628851     -0.002095 -0.608622   
321200   0.152625  0.089154          -0.611454     -0.002095 -0.590969   
74901    0.251879  0.186815           2.730474     -0.002095  0.556485   
426895   0.152625  0.186815          -0.524470     -0.002095 -0.502703   

        SBA_Appv  MIS_Status  
148172 -0.606817           1  
744579 -0.609553           0  
321200 -0.565780           0  
74901   0.112702           1  
426895 -0.543894           0

We have created Feature extraction by making use of old variables in the following way


(1) Log_Disbursement which gives the natural logarithmic form of DisbursementGross variable

(2) Log_GrAppv the logarithmic version of the approved loan amount by the bank

(3) Log_SBA_Appv, the logarithmic amount of the approved loan that will be assisted by SBA 

(4) Log_BalanceGross, is the logarithmic amount of total amount in an account or the total value of a financial asset or liability before any deductions or adjustments are made.

(5) TotalJobs variable which is an addition of Createjobs(New people recruited) and RetainedJob (workers working before)

(6) IncomeToLoan its values are calculated by dividing the 'DisbursementGross' column by the 'SBA_Appv' column for each corresponding row. This ratio can help you analyze the relationship between the amount disbursed and the approved SBA loan amount in terms of income.

(7)  EmployeesToLoanRatio, its values are calculated by dividing the 'NoEmp' column (number of employees) by the 'SBA_Appv' column (approved SBA loan amount) for each corresponding row. This ratio can help you analyze the relationship between the number of employees and the size of the SBA loan approved for each entry in the dataset.

(8) JobPerLoan, its values are calculated by dividing the 'TotalJobs' column (representing the total number of jobs) by the 'SBA_Appv' column (approved SBA loan amount) for each corresponding row. This ratio can help you analyze the impact of the SBA loan on job creation or support, expressed as the number of jobs per unit of loan amount approved.

(9) Gauren_SBA_Appv, Its values are calculated by dividing the 'GrAppv' column (gross amount approved by the lender) by the 'SBA_Appv' column (the approved SBA loan amount) for each corresponding row. This ratio helps you analyze the extent to which the SBA is guaranteeing the loan relative to the total loan amount approved by the lender.

(10) DefaultRate, Finally, we create a new feature 'DefaultRate' in the 'train_encoded' DataFrame and set its value to the calculated default rate for the particular group of loans based on the "MIS_Status" variable. This feature will represent the percentage of loans in the group that are classified as defaults.

In [142]:
# Adding Features
import numpy as np
# Apply the log transformation to the specific feature in your training data
#small_constant = 1e-10  # You can adjust this constant as needed
# df['LogColumn'] = np.log(df['OriginalColumn'] + small_constant)
train_encoded['Log_DisbursementGross'] = np.log1p(train_encoded['DisbursementGross'])
train_encoded['Log_GrAppv'] = np.log1p(train_encoded['GrAppv'])
train_encoded['Log_SBA_Appv'] = np.log1p(train_encoded['SBA_Appv'])
train_encoded['Log_BalanceGross'] = np.log1p(train_encoded['BalanceGross'])
train_encoded['TotalJobs'] = train_encoded['CreateJob'] + train_encoded['RetainedJob']
#train_encoded['Loan_Efficiency'] = train_encoded['DisbursementGross'] / (train_encoded['CreateJob'] + train_encoded['RetainedJob'] + 1)
# Calculate 'LoanToIncomeRatio' as a ratio of 'SBA_Appv' to 'DisbursementGross'
train_encoded['IncomeToLoanRatio'] = train_encoded['DisbursementGross'] / train_encoded['SBA_Appv']
# Calculate 'LoanToEmployeesRatio' as a ratio of 'SBA_Appv' to 'NoEmp'
train_encoded['EmployeesToLoanRatio'] = train_encoded['NoEmp'] / train_encoded['SBA_Appv']
# Create a binary feature to indicate loans with a balance ('BalanceGross' > 0)
#train_encoded['HasBalance'] = (train_encoded['BalanceGross'] > 0).astype(int)
# Calculate 'LoanPerJob' as a ratio of 'SBA_Appv' to 'TotalJobs'
train_encoded['JobPerLoan'] = train_encoded['TotalJobs'] / train_encoded['SBA_Appv'] 
# Calculate SBA's Gaurenteed Portion of Approved Loan
train_encoded['Gauren_SBA_Appv'] = train_encoded['GrAppv'] / train_encoded['SBA_Appv']
# Filter the DataFrame to include only the relevant rows
default_group = train_encoded[train_encoded['MIS_Status'].isin([0, 1])]
# Calculate the total number of loans in the filtered group
total_loans = len(default_group)
# Calculate the number of defaults (CHGOFF) in the filtered group
default_loans = len(default_group[default_group['MIS_Status'] == 1])
# Calculate the default rate as a percentage
default_rate = (default_loans / total_loans) * 100
# Create a new feature 'DefaultRate' with the calculated default rate
train_encoded['DefaultRate'] = default_rate

In [143]:
# Adding Features
import numpy as np
# Apply the log transformation to the specific feature in your training data
#small_constant = 1e-10  # You can adjust this constant as needed
# df['LogColumn'] = np.log(df['OriginalColumn'] + small_constant)
test_encoded['Log_DisbursementGross'] = np.log1p(test_encoded['DisbursementGross'])
test_encoded['Log_GrAppv'] = np.log1p(test_encoded['GrAppv'])
test_encoded['Log_SBA_Appv'] = np.log1p(test_encoded['SBA_Appv'])
test_encoded['Log_BalanceGross'] = np.log1p(test_encoded['BalanceGross'])
test_encoded['TotalJobs'] = test_encoded['CreateJob'] + test_encoded['RetainedJob']
#train_encoded['Loan_Efficiency'] = train_encoded['DisbursementGross'] / (train_encoded['CreateJob'] + train_encoded['RetainedJob'] + 1)
# Calculate 'LoanToIncomeRatio' as a ratio of 'SBA_Appv' to 'DisbursementGross'
test_encoded['IncomeToLoanRatio'] = test_encoded['DisbursementGross'] / test_encoded['SBA_Appv']
# Calculate 'LoanToEmployeesRatio' as a ratio of 'SBA_Appv' to 'NoEmp'
test_encoded['EmployeesToLoanRatio'] = test_encoded['NoEmp'] / test_encoded['SBA_Appv']
# Create a binary feature to indicate loans with a balance ('BalanceGross' > 0)
#train_encoded['HasBalance'] = (train_encoded['BalanceGross'] > 0).astype(int)
# Calculate 'LoanPerJob' as a ratio of 'SBA_Appv' to 'TotalJobs'
test_encoded['JobPerLoan'] = test_encoded['TotalJobs'] / test_encoded['SBA_Appv'] 
# Calculate SBA's Gaurenteed Portion of Approved Loan
test_encoded['Gauren_SBA_Appv'] = test_encoded['GrAppv'] / test_encoded['SBA_Appv']
# Filter the DataFrame to include only the relevant rows
default_group = test_encoded[test_encoded['MIS_Status'].isin([0, 1])]
# Calculate the total number of loans in the filtered group
total_loans = len(default_group)
# Calculate the number of defaults (CHGOFF) in the filtered group
default_loans = len(default_group[default_group['MIS_Status'] == 1])
# Calculate the default rate as a percentage
default_rate = (default_loans / total_loans) * 100
# Create a new feature 'DefaultRate' with the calculated default rate
test_encoded['DefaultRate'] = default_rate

In [144]:
train_encoded.columns

Index(['City', 'State', 'Zip', 'Bank', 'BankState', 'NAICS', 'NoEmp',
       'NewExist', 'CreateJob', 'RetainedJob', 'FranchiseCode', 'UrbanRural',
       'RevLineCr', 'LowDoc', 'DisbursementGross', 'BalanceGross', 'GrAppv',
       'SBA_Appv', 'MIS_Status', 'Log_DisbursementGross', 'Log_GrAppv',
       'Log_SBA_Appv', 'Log_BalanceGross', 'TotalJobs', 'IncomeToLoanRatio',
       'EmployeesToLoanRatio', 'JobPerLoan', 'Gauren_SBA_Appv', 'DefaultRate'],
      dtype='object')

In [145]:
X_train = train_encoded.copy()
X_test = test_encoded.copy()

In [146]:
y_train = X_train['MIS_Status']
X_train.drop(columns='MIS_Status', axis=1, inplace=True)
y_test = X_test['MIS_Status']
X_test.drop(columns='MIS_Status', axis=1, inplace=True)


In [147]:
import lightgbm as lgb
from sklearn.metrics import roc_auc_score

train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1})
test_data = lgb.Dataset(data=X_test, label=y_test, params={"verbose":-1})
lgb_clf = lgb.train(params={"verbose":-1},
                    train_set=train_data)

In [148]:
from sklearn.metrics import roc_auc_score
print("AUC score on Test dataset:", roc_auc_score(y_test, lgb_clf.predict(X_test)))
print("AUC score on Train dataset:", roc_auc_score(y_train, lgb_clf.predict(X_train)))

AUC score on Test dataset: 0.8205511277259651
AUC score on Train dataset: 0.8468756526040521


In [149]:
from optuna.integration import LightGBMPruningCallback
import tqdm as notebook_tqdm
from sklearn.model_selection import StratifiedKFold
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
import optuna
import warnings

warnings.filterwarnings("ignore", category=UserWarning)
study_model_iteractions = {}

def objective(trial, X, y):
    param_grid = {
        # Refer to the Official guide : https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
        "num_iterations": 10000,
        "num_threads": 16,
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, step=0.05),
        #"num_leaves": trial.suggest_int("num_leaves", 50, 150, step=5),
        "num_leaves": trial.suggest_int("num_leaves", 20, 700, step=10),
        "max_depth": trial.suggest_int("max_depth", 5, 15, step=2),
        #"max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 100, 1000, step=100),
        ##############################
        'lambda_l1': trial.suggest_float('lambda_l1', 1e-2, 10.0, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2', 1e-2, 10.0, log=True),
        #"lambda_l1": trial.suggest_int("lambda_l1", 0, 100, step=5),
        #"lambda_l2": trial.suggest_int("lambda_l2", 0, 100, step=5),
        #"lambda_l1": trial.suggest_float("lambda_l1", 0.01, 0.1, step=0.01),
        #"lambda_l2": trial.suggest_float("lambda_l2", 0.01, 0.1, step=0.01),
        ########################
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.8, 1.0, step=0.1),
        "bagging_freq": trial.suggest_categorical("bagging_freq", [5]),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.8, 1.0, step=0.1),
        #######################
        "is_unbalance": trial.suggest_categorical("is_unbalance",[True, False]),
        ########################
        "verbose": -1,
        "objective":"binary",
        "metric":"auc",
        "num_threads": 12
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=1121218)

    cv_scores = np.empty(5)
    cv_iteractions = np.empty(5)
    for idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1}, categorical_feature=categorical_columns)
        valid_data = lgb.Dataset(data=X_test, label=y_test, params={"verbose":-1}, categorical_feature=categorical_columns)
        lgb_clf = lgb.train(params=param_grid,
                            train_set=train_data,
                            valid_sets=[valid_data],
                            categorical_feature=categorical_columns,
                            callbacks=[LightGBMPruningCallback(trial, "auc"),
                                        lgb.early_stopping(stopping_rounds=5)]  
                            )
        preds = lgb_clf.predict(X_test)
        cv_scores[idx] = roc_auc_score(y_test, preds)
        cv_iteractions[idx] = lgb_clf.best_iteration
    
    study_model_iteractions[trial.number] = np.mean(cv_iteractions)

    return np.mean(cv_scores)

In [150]:
study = optuna.create_study(direction="maximize", study_name="LGBM Classifier")
func = lambda trial: objective(trial, X_train, y_train)
study.optimize(func, n_trials=200)

[I 2023-12-08 21:42:35,448] A new study created in memory with name: LGBM Classifier


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[86]	valid_0's auc: 0.801753
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.800155
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.802386
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[95]	valid_0's auc: 0.800114
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[90]	valid_0's auc: 0.802763


[I 2023-12-08 21:42:49,240] Trial 0 finished with value: 0.8014343348349386 and parameters: {'learning_rate': 0.21000000000000002, 'num_leaves': 600, 'max_depth': 15, 'min_data_in_leaf': 800, 'lambda_l1': 0.5019369632951083, 'lambda_l2': 0.02254125301802005, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': False}. Best is trial 0 with value: 0.8014343348349386.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[134]	valid_0's auc: 0.80378
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[96]	valid_0's auc: 0.802099
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[84]	valid_0's auc: 0.804749
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[85]	valid_0's auc: 0.80121
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[131]	valid_0's auc: 0.804938


[I 2023-12-08 21:43:06,251] Trial 1 finished with value: 0.8033552839768964 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 120, 'max_depth': 15, 'min_data_in_leaf': 600, 'lambda_l1': 1.0009992511791672, 'lambda_l2': 2.8993975320767986, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 0.8, 'is_unbalance': False}. Best is trial 1 with value: 0.8033552839768964.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[87]	valid_0's auc: 0.802776
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[74]	valid_0's auc: 0.801972
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[72]	valid_0's auc: 0.804005
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[80]	valid_0's auc: 0.801175
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[92]	valid_0's auc: 0.802756


[I 2023-12-08 21:43:22,716] Trial 2 finished with value: 0.802536988114316 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 330, 'max_depth': 13, 'min_data_in_leaf': 400, 'lambda_l1': 0.4946893198798722, 'lambda_l2': 0.012401785995639918, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 1 with value: 0.8033552839768964.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[12]	valid_0's auc: 0.781565
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[11]	valid_0's auc: 0.782946
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[840]	valid_0's auc: 0.805161
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[12]	valid_0's auc: 0.781704
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[1189]	valid_0's auc: 0.805866


[I 2023-12-08 21:44:30,935] Trial 3 finished with value: 0.7914484583276552 and parameters: {'learning_rate': 0.01, 'num_leaves': 350, 'max_depth': 13, 'min_data_in_leaf': 600, 'lambda_l1': 0.11848544467399574, 'lambda_l2': 0.04070126082495083, 'bagging_fraction': 0.9, 'bagging_freq': 5, 'feature_fraction': 0.8, 'is_unbalance': False}. Best is trial 1 with value: 0.8033552839768964.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[92]	valid_0's auc: 0.803622
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[112]	valid_0's auc: 0.802773
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[82]	valid_0's auc: 0.80513
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[103]	valid_0's auc: 0.802192
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[111]	valid_0's auc: 0.805079


[I 2023-12-08 21:44:43,169] Trial 4 finished with value: 0.8037592499384228 and parameters: {'learning_rate': 0.21000000000000002, 'num_leaves': 680, 'max_depth': 9, 'min_data_in_leaf': 500, 'lambda_l1': 0.5202237597210938, 'lambda_l2': 0.010216851864761053, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 0.8, 'is_unbalance': False}. Best is trial 4 with value: 0.8037592499384228.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[77]	valid_0's auc: 0.803005
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.801062
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[88]	valid_0's auc: 0.805054
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[84]	valid_0's auc: 0.802001
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[103]	valid_0's auc: 0.804402


[I 2023-12-08 21:44:58,673] Trial 5 finished with value: 0.803104618211891 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 500, 'max_depth': 11, 'min_data_in_leaf': 300, 'lambda_l1': 0.9787974235525188, 'lambda_l2': 0.22133344374978123, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 4 with value: 0.8037592499384228.
[I 2023-12-08 21:44:59,165] Trial 6 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:44:59,666] Trial 7 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:00,127] Trial 8 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:00,662] Trial 9 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:01,248] Trial 10 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:01,785] Trial 11 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:02,292] Trial 12 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:02,892] Trial 13 pruned. Trial was prune

Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[48]	valid_0's auc: 0.801936
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[38]	valid_0's auc: 0.800774
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[45]	valid_0's auc: 0.803156
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[45]	valid_0's auc: 0.800259
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[44]	valid_0's auc: 0.802773


[I 2023-12-08 21:45:16,281] Trial 18 finished with value: 0.8017795797707208 and parameters: {'learning_rate': 0.26, 'num_leaves': 550, 'max_depth': 15, 'min_data_in_leaf': 400, 'lambda_l1': 0.835277936148312, 'lambda_l2': 0.4484188292304997, 'bagging_fraction': 0.9, 'bagging_freq': 5, 'feature_fraction': 0.8, 'is_unbalance': False}. Best is trial 4 with value: 0.8037592499384228.
[I 2023-12-08 21:45:16,781] Trial 19 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:17,271] Trial 20 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[85]	valid_0's auc: 0.803245
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.801758
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[68]	valid_0's auc: 0.805084
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[62]	valid_0's auc: 0.80141
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[75]	valid_0's auc: 0.804334


[I 2023-12-08 21:45:31,730] Trial 21 finished with value: 0.8031661198776447 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 700, 'max_depth': 11, 'min_data_in_leaf': 200, 'lambda_l1': 1.035723033799241, 'lambda_l2': 0.30617848486664295, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 4 with value: 0.8037592499384228.
[I 2023-12-08 21:45:32,232] Trial 22 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:32,743] Trial 23 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:33,306] Trial 24 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:33,876] Trial 25 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.803323
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.80233
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[80]	valid_0's auc: 0.806436
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[109]	valid_0's auc: 0.80291
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[75]	valid_0's auc: 0.804379


[I 2023-12-08 21:45:50,078] Trial 26 finished with value: 0.8038756746130302 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 530, 'max_depth': 11, 'min_data_in_leaf': 200, 'lambda_l1': 1.7269826111545732, 'lambda_l2': 0.25399485674500827, 'bagging_fraction': 0.9, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 26 with value: 0.8038756746130302.
[I 2023-12-08 21:45:50,552] Trial 27 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:51,076] Trial 28 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:51,684] Trial 29 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:45:52,267] Trial 30 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[81]	valid_0's auc: 0.803795
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.80167
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.804703
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[78]	valid_0's auc: 0.801216
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[79]	valid_0's auc: 0.803767


[I 2023-12-08 21:46:07,240] Trial 31 finished with value: 0.8030301640981194 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 700, 'max_depth': 11, 'min_data_in_leaf': 200, 'lambda_l1': 1.1416126323028555, 'lambda_l2': 0.28495095797392916, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 26 with value: 0.8038756746130302.
[I 2023-12-08 21:46:07,749] Trial 32 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:46:08,365] Trial 33 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:46:08,948] Trial 34 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[68]	valid_0's auc: 0.803714
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.802915
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.806026
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.802304
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[75]	valid_0's auc: 0.805928


[I 2023-12-08 21:46:22,934] Trial 35 finished with value: 0.8041774035640923 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 460, 'max_depth': 13, 'min_data_in_leaf': 200, 'lambda_l1': 1.342771014406765, 'lambda_l2': 0.17194645073771586, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 35 with value: 0.8041774035640923.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[92]	valid_0's auc: 0.804801
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[68]	valid_0's auc: 0.802438
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.805844
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.802031
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[74]	valid_0's auc: 0.80529


[I 2023-12-08 21:46:36,763] Trial 36 finished with value: 0.8040808577349583 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 370, 'max_depth': 13, 'min_data_in_leaf': 300, 'lambda_l1': 1.6126827444489302, 'lambda_l2': 0.025335997293718625, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 35 with value: 0.8041774035640923.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[80]	valid_0's auc: 0.804285
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.802437
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[54]	valid_0's auc: 0.804624
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[69]	valid_0's auc: 0.80203
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.804739


[I 2023-12-08 21:46:48,885] Trial 37 finished with value: 0.8036230517718547 and parameters: {'learning_rate': 0.21000000000000002, 'num_leaves': 370, 'max_depth': 13, 'min_data_in_leaf': 300, 'lambda_l1': 1.4814065474915035, 'lambda_l2': 0.0101627935417404, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 35 with value: 0.8041774035640923.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[42]	valid_0's auc: 0.803741
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[49]	valid_0's auc: 0.802788
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.805414
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[69]	valid_0's auc: 0.802431
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.804922


[I 2023-12-08 21:47:02,067] Trial 38 finished with value: 0.8038592033079436 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 450, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.4653769936025254, 'lambda_l2': 0.016763981276730917, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 35 with value: 0.8041774035640923.
[I 2023-12-08 21:47:02,664] Trial 39 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[53]	valid_0's auc: 0.803467
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[68]	valid_0's auc: 0.802823
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.805389
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.802381
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[56]	valid_0's auc: 0.805246


[I 2023-12-08 21:47:15,506] Trial 40 finished with value: 0.8038611936409554 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 460, 'max_depth': 13, 'min_data_in_leaf': 200, 'lambda_l1': 1.429256789911889, 'lambda_l2': 0.016027603901618212, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 35 with value: 0.8041774035640923.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[63]	valid_0's auc: 0.803967
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[73]	valid_0's auc: 0.803668
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.805716
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[53]	valid_0's auc: 0.802581
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.805068


[I 2023-12-08 21:47:28,105] Trial 41 finished with value: 0.8041998833588033 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 200, 'lambda_l1': 1.6486809750973213, 'lambda_l2': 0.01646153811045168, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 41 with value: 0.8041998833588033.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.803898
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.802848
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[54]	valid_0's auc: 0.805099
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[53]	valid_0's auc: 0.802456
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[97]	valid_0's auc: 0.806274


[I 2023-12-08 21:47:41,205] Trial 42 finished with value: 0.8041148605161605 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 370, 'max_depth': 13, 'min_data_in_leaf': 200, 'lambda_l1': 1.3927190261293332, 'lambda_l2': 0.027011193607958475, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 41 with value: 0.8041998833588033.
[I 2023-12-08 21:47:41,786] Trial 43 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:47:42,351] Trial 44 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:47:42,986] Trial 45 pruned. Trial was pruned at iteration 3.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:47:43,536] Trial 46 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:47:44,504] Trial 47 pruned. Trial was pruned at iteration 11.
[I 2023-12-08 21:47:45,069] Trial 48 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:47:45,607] Trial 49 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:47:46,186] Trial 50 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[72]	valid_0's auc: 0.804145
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[70]	valid_0's auc: 0.802708
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[79]	valid_0's auc: 0.805502
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.80265
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.805537


[I 2023-12-08 21:48:00,574] Trial 51 finished with value: 0.8041085724684789 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 470, 'max_depth': 13, 'min_data_in_leaf': 200, 'lambda_l1': 1.4282758342763142, 'lambda_l2': 0.015256916081259004, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 41 with value: 0.8041998833588033.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.804738
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.802608
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.806023
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.802948
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[79]	valid_0's auc: 0.805228


[I 2023-12-08 21:48:14,239] Trial 52 finished with value: 0.8043088881883189 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 2.0419310805102273, 'lambda_l2': 0.013339835168278942, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 52 with value: 0.8043088881883189.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.804881
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[51]	valid_0's auc: 0.803504
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.805555
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.802867
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:48:26,137] Trial 53 finished with value: 0.8043295959122133 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 390, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 2.2947110854879846, 'lambda_l2': 0.012044752572340792, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 53 with value: 0.8043295959122133.


Early stopping, best iteration is:
[44]	valid_0's auc: 0.804841
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[57]	valid_0's auc: 0.803559
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.802314
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.80545
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[46]	valid_0's auc: 0.802328
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.805348


[I 2023-12-08 21:48:39,427] Trial 54 finished with value: 0.8037996367779854 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 480, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 3.10337012237072, 'lambda_l2': 0.012731435462823166, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 53 with value: 0.8043295959122133.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.804139
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[51]	valid_0's auc: 0.802798
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[39]	valid_0's auc: 0.805209
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.80292
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[44]	valid_0's auc: 0.805035


[I 2023-12-08 21:48:52,318] Trial 55 finished with value: 0.804020187950365 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 430, 'max_depth': 15, 'min_data_in_leaf': 100, 'lambda_l1': 2.177739790346209, 'lambda_l2': 0.010710164798534955, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 53 with value: 0.8043295959122133.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[43]	valid_0's auc: 0.803373
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[29]	valid_0's auc: 0.801321
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[42]	valid_0's auc: 0.804504
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[44]	valid_0's auc: 0.802026
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:02,209] Trial 56 finished with value: 0.8031707416285586 and parameters: {'learning_rate': 0.21000000000000002, 'num_leaves': 390, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.202977610240069, 'lambda_l2': 0.015309728521150751, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 53 with value: 0.8043295959122133.


Early stopping, best iteration is:
[48]	valid_0's auc: 0.80463


[I 2023-12-08 21:49:02,772] Trial 57 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:03,528] Trial 58 pruned. Trial was pruned at iteration 4.
[I 2023-12-08 21:49:04,101] Trial 59 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:49:04,766] Trial 60 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:05,309] Trial 61 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:07,225] Trial 62 pruned. Trial was pruned at iteration 35.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:08,031] Trial 63 pruned. Trial was pruned at iteration 6.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[73]	valid_0's auc: 0.804756
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[53]	valid_0's auc: 0.803031
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.806228
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.802835
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:20,314] Trial 64 finished with value: 0.8044799022503313 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 290, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.9109895189675501, 'lambda_l2': 0.024978280416284533, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 64 with value: 0.8044799022503313.


Early stopping, best iteration is:
[53]	valid_0's auc: 0.80555


[I 2023-12-08 21:49:20,831] Trial 65 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[37]	valid_0's auc: 0.802684
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[35]	valid_0's auc: 0.801614
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[34]	valid_0's auc: 0.804006
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:28,608] Trial 66 pruned. Trial was pruned at iteration 42.
[I 2023-12-08 21:49:29,178] Trial 67 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:29,712] Trial 68 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:49:30,218] Trial 69 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:49:30,862] Trial 70 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:31,424] Trial 71 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:49:32,015] Trial 72 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:32,564] Trial 73 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:49:33,231] Trial 74 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:49:33,747] Trial 75 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.804304
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[69]	valid_0's auc: 0.803467
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[50]	valid_0's auc: 0.805369
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.802902
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.80616


[I 2023-12-08 21:49:47,174] Trial 76 finished with value: 0.8044403955845695 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 370, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 2.397682879917814, 'lambda_l2': 0.038209738563430115, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 64 with value: 0.8044799022503313.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[54]	valid_0's auc: 0.803825
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[56]	valid_0's auc: 0.802664
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.805499
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.802864
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[69]	valid_0's auc: 0.805323


[I 2023-12-08 21:50:00,567] Trial 77 finished with value: 0.8040350553168318 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 440, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 2.3660595694696056, 'lambda_l2': 0.06303039857904925, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 64 with value: 0.8044799022503313.
[I 2023-12-08 21:50:01,072] Trial 78 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:50:03,298] Trial 79 pruned. Trial was pruned at iteration 43.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:50:04,992] Trial 80 pruned. Trial was pruned at iteration 32.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[50]	valid_0's auc: 0.804127
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.803452
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.805607
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[54]	valid_0's auc: 0.802014
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.805395


[I 2023-12-08 21:50:17,770] Trial 81 finished with value: 0.8041186762340986 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.594821830830782, 'lambda_l2': 0.02356400222007002, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 64 with value: 0.8044799022503313.
[I 2023-12-08 21:50:18,350] Trial 82 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.804352
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[51]	valid_0's auc: 0.802656
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[53]	valid_0's auc: 0.8059
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.802359
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[68]	valid_0's auc: 0.805573


[I 2023-12-08 21:50:31,396] Trial 83 finished with value: 0.8041679322627875 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 410, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.3077730480104564, 'lambda_l2': 0.011639258303826628, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 64 with value: 0.8044799022503313.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.804487
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.803316
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[54]	valid_0's auc: 0.805743
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[69]	valid_0's auc: 0.80337
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.806141


[I 2023-12-08 21:50:44,546] Trial 84 finished with value: 0.8046114150178705 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.8143630422709964, 'lambda_l2': 0.011498433150379532, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:50:45,077] Trial 85 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:50:45,579] Trial 86 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:50:46,128] Trial 87 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[63]	valid_0's auc: 0.804275
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[56]	valid_0's auc: 0.80265
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.806545
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[62]	valid_0's auc: 0.802561
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:50:58,776] Trial 88 finished with value: 0.8041832212938385 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.7788412929204277, 'lambda_l2': 0.014643246918487122, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Early stopping, best iteration is:
[55]	valid_0's auc: 0.804886


[I 2023-12-08 21:50:59,294] Trial 89 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.804426
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.80292
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[46]	valid_0's auc: 0.805455
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.802665
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.80544


[I 2023-12-08 21:51:11,559] Trial 90 finished with value: 0.8041811259091926 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 350, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.6412952497291128, 'lambda_l2': 0.018308171082697132, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:51:13,483] Trial 91 pruned. Trial was pruned at iteration 45.
[I 2023-12-08 21:51:14,092] Trial 92 pruned. Trial was pruned at iteration 3.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:51:14,692] Trial 93 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.804519
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[49]	valid_0's auc: 0.803157
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[45]	valid_0's auc: 0.805975
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[70]	valid_0's auc: 0.803126
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:51:26,976] Trial 94 finished with value: 0.8044613715959799 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 330, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.6151547747185434, 'lambda_l2': 0.01754409574030045, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Early stopping, best iteration is:
[53]	valid_0's auc: 0.80553


[I 2023-12-08 21:51:27,507] Trial 95 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[63]	valid_0's auc: 0.804509
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.80296
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.806625
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[47]	valid_0's auc: 0.802026
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[71]	valid_0's auc: 0.805825


[I 2023-12-08 21:51:40,628] Trial 96 finished with value: 0.8043891457148222 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 350, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.6018146118800104, 'lambda_l2': 0.029038500955045038, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:51:41,138] Trial 97 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[56]	valid_0's auc: 0.804657
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[48]	valid_0's auc: 0.802901
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[54]	valid_0's auc: 0.806131
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[49]	valid_0's auc: 0.80213
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.805602


[I 2023-12-08 21:51:52,853] Trial 98 finished with value: 0.8042841885317843 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 350, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.6177964142618628, 'lambda_l2': 0.02032115275372723, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.804277
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[51]	valid_0's auc: 0.802906
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.806074
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[56]	valid_0's auc: 0.802501
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[67]	valid_0's auc: 0.805408


[I 2023-12-08 21:52:05,385] Trial 99 finished with value: 0.8042331470130373 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.739359805831142, 'lambda_l2': 0.020825185036235816, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:52:05,979] Trial 100 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:06,818] Trial 101 pruned. Trial was pruned at iteration 8.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:08,585] Trial 102 pruned. Trial was pruned at iteration 34.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:09,701] Trial 103 pruned. Trial was pruned at iteration 15.
[I 2023-12-08 21:52:10,273] Trial 104 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.804305
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.802997
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[46]	valid_0's auc: 0.806005
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.802636
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.805375


[I 2023-12-08 21:52:22,608] Trial 105 finished with value: 0.8042636009702996 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 390, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.58797631661029, 'lambda_l2': 0.034142593618893366, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:52:23,149] Trial 106 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:52:23,716] Trial 107 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:24,266] Trial 108 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:52:24,799] Trial 109 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:52:25,299] Trial 110 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:26,805] Trial 111 pruned. Trial was pruned at iteration 24.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:27,932] Trial 112 pruned. Trial was pruned at iteration 15.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:28,799] Trial 113 pruned. Trial was pruned at iteration 8.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:30,765] Trial 114 pruned. Trial was pruned at iteration 40.
[I 2023-12-08 21:52:31,298] Trial 115 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:52:31,815] Trial 116 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:33,065] Trial 117 pruned. Trial was pruned at iteration 17.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:34,231] Trial 118 pruned. Trial was pruned at iteration 17.
[I 2023-12-08 21:52:34,754] Trial 119 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:52:35,282] Trial 120 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:36,264] Trial 121 pruned. Trial was pruned at iteration 12.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:37,451] Trial 122 pruned. Trial was pruned at iteration 17.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:38,497] Trial 123 pruned. Trial was pruned at iteration 12.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:39,864] Trial 124 pruned. Trial was pruned at iteration 22.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:41,030] Trial 125 pruned. Trial was pruned at iteration 15.
[I 2023-12-08 21:52:41,564] Trial 126 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[62]	valid_0's auc: 0.804471
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[46]	valid_0's auc: 0.80297
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.806138
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[50]	valid_0's auc: 0.802348
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.805721


[I 2023-12-08 21:52:54,062] Trial 127 finished with value: 0.8043295859541792 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 370, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.7461681705520031, 'lambda_l2': 0.01926038611893716, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:52:54,645] Trial 128 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:55,233] Trial 129 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:55,762] Trial 130 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:52:56,432] Trial 131 pruned. Trial was pruned at iteration 4.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:57,216] Trial 132 pruned. Trial was pruned at iteration 6.
[I 2023-12-08 21:52:57,812] Trial 133 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:52:58,862] Trial 134 pruned. Trial was pruned at iteration 13.
[I 2023-12-08 21:52:59,461] Trial 135 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:00,013] Trial 136 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:00,561] Trial 137 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:01,138] Trial 138 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:01,736] Trial 139 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:02,294] Trial 140 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:02,877] Trial 141 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:03,628] Trial 142 pruned. Trial was pruned at iteration 6.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:04,350] Trial 143 pruned. Trial was pruned at iteration 5.
[I 2023-12-08 21:53:04,928] Trial 144 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:05,527] Trial 145 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:06,044] Trial 146 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:06,577] Trial 147 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:07,194] Trial 148 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:07,700] Trial 149 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:53:08,209] Trial 150 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:09,122] Trial 151 pruned. Trial was pruned at iteration 9.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.80413
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.802546
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[50]	valid_0's auc: 0.805645
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[79]	valid_0's auc: 0.803397
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[58]	valid_0's auc: 0.804714


[I 2023-12-08 21:53:22,341] Trial 152 finished with value: 0.8040862766933283 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 410, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.612987060411111, 'lambda_l2': 0.015221657841184707, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:23,908] Trial 153 pruned. Trial was pruned at iteration 29.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:25,424] Trial 154 pruned. Trial was pruned at iteration 29.
[I 2023-12-08 21:53:25,975] Trial 155 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:28,424] Trial 156 pruned. Trial was pruned at iteration 52.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:29,219] Trial 157 pruned. Trial was pruned at iteration 6.
[I 2023-12-08 21:53:29,757] Trial 158 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:30,575] Trial 159 pruned. Trial was pruned at iteration 6.
[I 2023-12-08 21:53:31,124] Trial 160 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[47]	valid_0's auc: 0.804262
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.80356
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[65]	valid_0's auc: 0.806071
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[43]	valid_0's auc: 0.802137
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.805845


[I 2023-12-08 21:53:43,429] Trial 161 finished with value: 0.804374785695438 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.6715621952706468, 'lambda_l2': 0.021809221548346774, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[49]	valid_0's auc: 0.803859
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:48,260] Trial 162 pruned. Trial was pruned at iteration 58.
[I 2023-12-08 21:53:48,806] Trial 163 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:49,638] Trial 164 pruned. Trial was pruned at iteration 8.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:53:50,779] Trial 165 pruned. Trial was pruned at iteration 15.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[50]	valid_0's auc: 0.804274
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.802988
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.805461
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.802233
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[69]	valid_0's auc: 0.80544


[I 2023-12-08 21:54:03,142] Trial 166 finished with value: 0.8040793643469211 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.1302267432332307, 'lambda_l2': 0.024978273082551322, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:54:03,693] Trial 167 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:04,268] Trial 168 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:05,257] Trial 169 pruned. Trial was pruned at iteration 11.
[I 2023-12-08 21:54:05,802] Trial 170 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[56]	valid_0's auc: 0.804911
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[55]	valid_0's auc: 0.803431
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[59]	valid_0's auc: 0.805941
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[71]	valid_0's auc: 0.802867
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[50]	valid_0's auc: 0.804491


[I 2023-12-08 21:54:18,527] Trial 171 finished with value: 0.8043279781797896 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 1.676290197015179, 'lambda_l2': 0.022992018078717202, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:54:19,140] Trial 172 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:20,020] Trial 173 pruned. Trial was pruned at iteration 9.
[I 2023-12-08 21:54:20,584] Trial 174 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:21,326] Trial 175 pruned. Trial was pruned at iteration 6.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[60]	valid_0's auc: 0.804331
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[42]	valid_0's auc: 0.802252
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[44]	valid_0's auc: 0.80525
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[64]	valid_0's auc: 0.803179
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[73]	valid_0's auc: 0.806059


[I 2023-12-08 21:54:34,251] Trial 176 finished with value: 0.8042139811792938 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 400, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 2.0348896359034083, 'lambda_l2': 0.023931463533413487, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.
[I 2023-12-08 21:54:34,804] Trial 177 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:35,430] Trial 178 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:35,986] Trial 179 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:36,561] Trial 180 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:37,118] Trial 181 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:37,982] Trial 182 pruned. Trial was pruned at iteration 8.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:38,865] Trial 183 pruned. Trial was pruned at iteration 8.
[I 2023-12-08 21:54:39,456] Trial 184 pruned. Trial was pruned at iteration 1.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:40,291] Trial 185 pruned. Trial was pruned at iteration 7.
[I 2023-12-08 21:54:40,849] Trial 186 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:41,384] Trial 187 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:41,915] Trial 188 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:42,492] Trial 189 pruned. Trial was pruned at iteration 0.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:43,537] Trial 190 pruned. Trial was pruned at iteration 12.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:44,804] Trial 191 pruned. Trial was pruned at iteration 17.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:45,822] Trial 192 pruned. Trial was pruned at iteration 12.
[I 2023-12-08 21:54:46,351] Trial 193 pruned. Trial was pruned at iteration 0.
[I 2023-12-08 21:54:46,997] Trial 194 pruned. Trial was pruned at iteration 2.


Training until validation scores don't improve for 5 rounds
Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:47,840] Trial 195 pruned. Trial was pruned at iteration 8.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:49,538] Trial 196 pruned. Trial was pruned at iteration 29.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:54:50,306] Trial 197 pruned. Trial was pruned at iteration 5.


Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[48]	valid_0's auc: 0.804164
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[52]	valid_0's auc: 0.803334
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[48]	valid_0's auc: 0.80593
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[66]	valid_0's auc: 0.802057
Training until validation scores don't improve for 5 rounds
Early stopping, best iteration is:
[61]	valid_0's auc: 0.805321


[I 2023-12-08 21:55:03,159] Trial 198 finished with value: 0.8041612288067324 and parameters: {'learning_rate': 0.16000000000000003, 'num_leaves': 390, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.5597494879262164, 'lambda_l2': 0.019873106892296235, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True}. Best is trial 84 with value: 0.8046114150178705.


Training until validation scores don't improve for 5 rounds


[I 2023-12-08 21:55:04,753] Trial 199 pruned. Trial was pruned at iteration 29.


In [151]:
import pickle

# Assuming you have a variable named 'best_params' containing the best hyperparameters
best_params = study.best_params

with open('best_params.pkl', 'wb') as f:
    pickle.dump(best_params, f)

In [167]:
best_params


{'verbose': -1,
 'objective': 'binary',
 'metric': 'auc',
 'learning_rate': 0.16000000000000003,
 'num_leaves': 380,
 'max_depth': 13,
 'min_data_in_leaf': 100,
 'lambda_l1': 0.8143630422709964,
 'lambda_l2': 0.011498433150379532,
 'bagging_fraction': 1.0,
 'bagging_freq': 5,
 'feature_fraction': 1.0,
 'is_unbalance': True,
 'num_iterations': 63}

In [168]:
from sklearn.metrics import f1_score
import numpy as np

def calculate_optimal_threshold(classifier, X, y):
    # Predict probabilities
    y_pred_proba = classifier.predict(X)
    
    # Set a range of thresholds to test
    thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    best_f1 = 0
    best_threshold = 0
    
    # Find the threshold that maximizes the F1 score
    for threshold in thresholds:
      y_pred = (y_pred_proba > threshold).astype(int)
      f1 = f1_score(y_test, y_pred, average='macro')
    
      if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
    return best_threshold

In [169]:
print(f"\tBest value (AUC): {study.best_value:.5f}")
print(f"\tBest params:")

for key, value in study.best_params.items():
    print(f"\t\t{key}: {value}")

print("Best model best_iteration:", study_model_iteractions[study.best_trial.number])

	Best value (AUC): 0.80461
	Best params:
		learning_rate: 0.16000000000000003
		num_leaves: 380
		max_depth: 13
		min_data_in_leaf: 100
		lambda_l1: 0.8143630422709964
		lambda_l2: 0.011498433150379532
		bagging_fraction: 1.0
		bagging_freq: 5
		feature_fraction: 1.0
		is_unbalance: True
Best model best_iteration: 63.2


In [170]:
best_params = {"verbose": -1,
                "objective":"binary",
                "metric":"auc"
            }
for key,val in study.best_params.items():
    best_params[key] = val

best_params["num_iterations"] = int(study_model_iteractions[study.best_trial.number])
print(best_params)

{'verbose': -1, 'objective': 'binary', 'metric': 'auc', 'learning_rate': 0.16000000000000003, 'num_leaves': 380, 'max_depth': 13, 'min_data_in_leaf': 100, 'lambda_l1': 0.8143630422709964, 'lambda_l2': 0.011498433150379532, 'bagging_fraction': 1.0, 'bagging_freq': 5, 'feature_fraction': 1.0, 'is_unbalance': True, 'num_iterations': 63}


# Training the model with parameters found using Optuna

In [171]:

train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1}, categorical_feature=categorical_columns)
test_data = lgb.Dataset(data=X_test, label=y_test, params={"verbose":-1}, categorical_feature=categorical_columns)
best_lgb = lgb.train(params=best_params,
                    train_set=train_data) 

In [172]:
print("AUC score on Test dataset:", roc_auc_score(y_test, best_lgb.predict(X_test)))
print("AUC score on Train dataset:", roc_auc_score(y_train, best_lgb.predict(X_train)))

AUC score on Test dataset: 0.8080452240164088
AUC score on Train dataset: 0.8479345099436233


In [173]:
from sklearn.metrics import f1_score
import numpy as np

def calculate_optimal_threshold(classifier, X, y):
    # Predict probabilities
    y_pred_proba = classifier.predict(X)
    
    # Set a range of thresholds to test
    thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    best_f1 = 0
    best_threshold = 0
    
    # Find the threshold that maximizes the F1 score
    for threshold in thresholds:
      y_pred = (y_pred_proba > threshold).astype(int)
      f1 = f1_score(y_test, y_pred, average='macro')
    
      if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
    return best_threshold
    
   

In [174]:
calculate_optimal_threshold(best_lgb, X_test, y_test)

0.7

In [175]:
from sklearn.metrics import f1_score

# Assuming best_lgb is the trained LightGBM model and X_test, y_test are defined

# Get the predicted probabilities for the positive class (class 1)
y_pred_proba = best_lgb.predict(X_test)

# Set a range of thresholds to test
thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

best_f1 = 0
best_threshold = 0

# Find the threshold that maximizes the F1 score
for threshold in thresholds:
    y_pred = (y_pred_proba > threshold).astype(int)
    f1 = f1_score(y_test, y_pred, average='macro')
    
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold

print("Best F1 score:", best_f1)
print("Best threshold:", best_threshold)

Best F1 score: 0.6879352668818348
Best threshold: 0.7


In [177]:
from sklearn.metrics import confusion_matrix
# Get the predicted probabilities for the positive class (class 1) from the test set
y_pred_proba = best_lgb.predict(X_test)

# Use the threshold obtained earlier to predict binary labels
threshold = best_threshold
y_pred = (y_pred_proba > threshold).astype(int)

# Construct the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[179678  18222]
 [ 23150  19027]]


In [178]:
import pickle

# Assuming you have a variable named 'best_params' containing the best hyperparameters
best_params = best_params

with open('best_params.pkl', 'wb') as f:
    pickle.dump(best_params, f)

In [179]:
from sklearn.metrics import f1_score
import numpy as np

def calculate_optimal_threshold(classifier, X, y):
    # Predict probabilities
    y_pred_proba = classifier.predict(X)
    
    # Set a range of thresholds to test
    thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    best_f1 = 0
    best_threshold = 0
    
    # Find the threshold that maximizes the F1 score
    for threshold in thresholds:
      y_pred = (y_pred_proba > threshold).astype(int)
      f1 = f1_score(y_test, y_pred, average='macro')
    
      if f1 > best_f1:
        best_f1 = f1
        best_threshold = threshold
    return best_threshold

In [180]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import category_encoders as ce
from copy import deepcopy

def train_model(df):
    """
    Train sample model and save artifacts
    """
    from sklearn.linear_model import LogisticRegression
    from optuna.integration import LightGBMPruningCallback
    import tqdm as notebook_tqdm
    from sklearn.model_selection import StratifiedKFold
    import lightgbm as lgb
    from sklearn.metrics import roc_auc_score
    import optuna
    import warnings
    import pickle
    from sklearn.impute import SimpleImputer
    from sklearn.model_selection import GridSearchCV
    from sklearn.preprocessing import FunctionTransformer
    from sklearn.metrics import average_precision_score
    import numpy as np
    import warnings
    warnings.simplefilter(action='ignore', category=FutureWarning)
    
    
    target_col = "MIS_Status"
    cols_to_drop = ['City', 'State', 'Zip','Bank', 'BankState', 'LowDoc','RevLineCr','MIS_Status']
    # Removing the index column
    if "index" in df.columns:
        df.drop(columns="index", inplace=True)
    y = df[target_col] if target_col in df.columns else None
    X = df.drop(columns=[target_col]) if target_col in df.columns else df.copy()


    # Relacing Missing values
    
    for i in df['RevLineCr']:
      if i not in ['Y','N']:
        df['RevLineCr'].replace(i,'N',inplace=True)
        print("RevLineCr",df['RevLineCr'].unique())

    for i in df['LowDoc']:
      if i not in ['Y','N']:
        df['LowDoc'].replace(i,'N',inplace=True)
        print("LowDoc",df['LowDoc'].unique())

    for i in df['NewExist']:
      if i not in [1,2]:
        df['NewExist'].replace(i,None,inplace=True)
        print("NewExist",df['NewExist'].unique())


    category_cols=['City', 'State', 'Bank', 'BankState', 'RevLineCr', 'LowDoc','NewExist']
    for column in category_cols:
        df[column]=df[column].fillna(df[column].mode()[0])

    # Target encoding the categorical columns
    categorical_columns = ['City', 'State', 'Bank', 'BankState', 'RevLineCr', 'LowDoc','NewExist']
    encoder = ce.TargetEncoder(cols=categorical_columns)
    encoder.fit(df[categorical_columns], df['MIS_Status'])
    train_encoded = encoder.transform(df[categorical_columns])
    train_encoded = train_encoded.add_suffix('_trg')
    #train_encoded = pd.concat([train_encoded, data], axis=1)
    train_encoded = pd.concat([train_encoded, df], axis=1)
    for column in categorical_columns:
        train_encoded[column + "_trg"].fillna(train_encoded[column + "_trg"].mean(), inplace=True)
    
    # Renaming the columns
    #train_encoded.rename(columns={col: col + "_trg" if col in categorical_columns else col for col in train_encoded.columns}, inplace=False)
    print(train_encoded.columns)
    


    # Adding Features
    import numpy as np
    # Apply the log transformation to the specific feature in your training data
    small_constant = 1e-10  # You can adjust this constant as needed
    # df['LogColumn'] = np.log(df['OriginalColumn'] + small_constant)
    train_encoded['Log_DisbursementGross'] = np.log1p(train_encoded['DisbursementGross'])
    train_encoded['Log_GrAppv'] = np.log1p(train_encoded['GrAppv'])
    train_encoded['Log_SBA_Appv'] = np.log1p(train_encoded['SBA_Appv'])
    train_encoded['Log_BalanceGross'] = np.log1p(train_encoded['BalanceGross'])
    train_encoded['TotalJobs'] = train_encoded['CreateJob'] + train_encoded['RetainedJob']
    #train_encoded['Loan_Efficiency'] = train_encoded['DisbursementGross'] / (train_encoded['CreateJob'] + train_encoded['RetainedJob'] + 1)
    # Calculate 'LoanToIncomeRatio' as a ratio of 'SBA_Appv' to 'DisbursementGross'
    train_encoded['IncomeToLoanRatio'] = train_encoded['DisbursementGross'] / train_encoded['SBA_Appv']
    # Calculate 'LoanToEmployeesRatio' as a ratio of 'SBA_Appv' to 'NoEmp'
    train_encoded['EmployeesToLoanRatio'] = train_encoded['NoEmp'] / train_encoded['SBA_Appv']
    # Create a binary feature to indicate loans with a balance ('BalanceGross' > 0)
    #train_encoded['HasBalance'] = (train_encoded['BalanceGross'] > 0).astype(int)
    # Calculate 'LoanPerJob' as a ratio of 'SBA_Appv' to 'TotalJobs'
    train_encoded['JobPerLoan'] = train_encoded['TotalJobs'] / train_encoded['SBA_Appv'] 
    # Calculate SBA's Gaurenteed Portion of Approved Loan
    train_encoded['Gauren_SBA_Appv'] = train_encoded['GrAppv'] / train_encoded['SBA_Appv']

    
    # Scaling the numerical columns
    numerical_columns = [ 'NoEmp', 'CreateJob', 'RetainedJob', 'GrAppv', 'SBA_Appv', 'DisbursementGross', 'BalanceGross',
                        'Log_DisbursementGross', 'Log_GrAppv', 'Log_SBA_Appv', 'Log_BalanceGross','TotalJobs','IncomeToLoanRatio', 
                        'EmployeesToLoanRatio', 'JobPerLoan', 'Gauren_SBA_Appv']
    
    scaler = StandardScaler()
    #fit and transform separately
    scaler.fit(train_encoded[numerical_columns])
    train_encoded[numerical_columns] = scaler.transform(train_encoded[numerical_columns])

    warnings.filterwarnings("ignore", category=UserWarning)
    study_model_iteractions = {}

    def objective(trial, X, y):
     
      param_grid = {
        # Refer to the Official guide : https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
        "num_iterations": 10000,
        "num_threads": 16,
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, step=0.05),
        #"num_leaves": trial.suggest_int("num_leaves", 50, 150, step=5),
        "num_leaves": trial.suggest_int("num_leaves", 20, 3000, step=20),
        #"max_depth": trial.suggest_int("max_depth", 5, 20, step=2),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 100, 1000, step=100),
        ##############################
        #'lambda_l1': trial.suggest_float('lambda_l1', 1e-8, 10.0, log=True),
        #'lambda_l2': trial.suggest_float('lambda_l2', 1e-8, 10.0, log=True),
        "lambda_l1": trial.suggest_int("lambda_l1", 0, 100, step=5),
        "lambda_l2": trial.suggest_int("lambda_l2", 0, 100, step=5),
        #"lambda_l1": trial.suggest_float("lambda_l1", 0.01, 0.1, step=0.01),
        #"lambda_l2": trial.suggest_float("lambda_l2", 0.01, 0.1, step=0.01),
        ########################
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.8, 1.0, step=0.1),
        "bagging_freq": trial.suggest_categorical("bagging_freq", [5]),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.8, 1.0, step=0.1),
        #######################
        "is_unbalance": trial.suggest_categorical("is_unbalance",[True, False]),
        ########################
        "verbose": -1,
        "objective":"binary",
        "metric":"auc",
        "num_threads": 12
       }

      cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=1121218)

      cv_scores = np.empty(5)
      cv_iteractions = np.empty(5)
      for idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        train_data = lgb.Dataset(data=X_train, label=y_train, params={"verbose":-1}, categorical_feature=categorical_columns)
        valid_data = lgb.Dataset(data=X_test, label=y_test, params={"verbose":-1}, categorical_feature=categorical_columns)
        lgb_clf = lgb.train(params=param_grid,
                            train_set=train_data,
                            valid_sets=[valid_data],
                            categorical_feature=categorical_columns,
                            callbacks=[LightGBMPruningCallback(trial, "auc"),
                                        lgb.early_stopping(stopping_rounds=5)]  
                            )
        preds = lgb_clf.predict(X_test)
        cv_scores[idx] = roc_auc_score(y_test, preds)
        cv_iteractions[idx] = lgb_clf.best_iteration
    
      study_model_iteractions[trial.number] = np.mean(cv_iteractions)

      return np.mean(cv_scores)

      study = optuna.create_study(direction="maximize", study_name="LGBM Classifier")
      func = lambda trial: objective(trial, X_train, y_train)
      study.optimize(func, n_trials=200)

      print(f"\tBest value (AUC): {study.best_value:.5f}")
      print(f"\tBest params:")

      for key, value in study.best_params.items():
        print(f"\t\t{key}: {value}")

      print("Best model best_iteration:", study_model_iteractions[study.best_trial.number])
      best_iterations = study_model_iteractions[study.best_trial.number] 

        
    

          
   
      # End Todo
    
      # Saving the artifacts
      artifacts_dict = {
        "model": lgb_clf,
        "target_encoder": encoder,
        "te_columns": categorical_columns,
        "columns_to_train":columns_to_train,
        "numerical_columns":numerical_columns,
        "category_cols": category_cols,
        "scaler":scaler
        #"h2o_model_path":model_path
      }

      #calculating threshold
      if y is not None:
        optimal_threshold = calculate_optimal_threshold(clf_, train_encoded[columns_to_train], y)
        print(f"Optimal Threshold: {optimal_threshold}")
        # Saving the threshold in artifacts
        artifacts_dict["threshold"] = optimal_threshold

      artifacts_dict_file = open("./Artifacts/artifacts_dict_file.pkl", "wb")
      pickle.dump(obj=artifacts_dict, file=artifacts_dict_file)    
       
      artifacts_dict_file.close()    
      return lgb_clf

In [181]:
from sklearn.model_selection import train_test_split
        
df = pd.read_csv("D:/Work/Gre/UTD/Courses/Fall/MIS6341/Softwares/Python/ml-fall-2023/Project2/SBA_loans_project_2.csv")
target = "MIS_Status"
y = df[target]
x = df.drop(columns=[target])

# Splitting the dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train.reset_index(inplace=True, drop=True)
y_train.reset_index(inplace=True, drop=True)
X_test.reset_index(inplace=True, drop=True)
y_test.reset_index(inplace=True, drop=True)
df_train = X_train.copy()
df_train[target] = y_train
train_model(df_train)

RevLineCr ['N' 'Y' 'T' nan '1' 'R' '`' 'Q' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' nan '1' 'R' '`' 'Q' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' '1' 'R' '`' 'Q' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' 'R' '`' 'Q' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' '`' 'Q' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' 'Q' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' '-' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' '7' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' '2' '4' '.' 'C']
RevLineCr ['N' 'Y' '4' '.' 'C']
RevLineCr ['N' 'Y' '.' 'C']
RevLineCr ['N' 'Y' 'C']
RevLineCr ['N' 'Y']
LowDoc ['N' 'Y' 'C' nan 'A' 'S' 'R']
LowDoc ['N' 'Y' nan 'A' 'S' 'R']
LowDoc ['N' 'Y' 'A' 'S' 'R']
LowDoc ['N' 'Y' 'S' 'R']
LowDoc ['N' 'Y' 'R']
LowDoc ['N' 'Y']
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 2.0 None nan]
NewExist [1.0 

In [182]:
def scoring(data):
    """
    Function to score input dataset.
    
    Input: dataset in Pandas DataFrame format
    Output: Python list of labels in the same order as input records
    
    Flow:
        - Load artifacts
        - Transform dataset
        - Score dataset
        - Return labels
    
    """
    
    if "index" in data.columns:
        data.drop(columns="index", inplace=True)
    #Load Artifacts
    artifacts_dict_file = open("./Artifacts/artifacts_dict_file.pkl", "rb")
    artifacts_dict = pickle.load(file=artifacts_dict_file)
    artifacts_dict_file.close()
    

    clf = artifacts_dict["model"]
    te = artifacts_dict["target_encoder"]
    te_columns = artifacts_dict["te_columns"]
    columns_to_score = artifacts_dict["columns_to_train"]
    threshold = artifacts_dict["threshold"]
    category_cols = artifacts_dict["category_cols"]
    numerical_columns = artifacts_dict["numerical_columns"]
    scaler = artifacts_dict["scaler"]

     # Replacing the missing values
    for i in data['RevLineCr']:
        if i not in ['Y','N']:
            data['RevLineCr'].replace(i,'N',inplace=True)

    for i in data['LowDoc']:
        if i not in ['Y','N']:
            data['LowDoc'].replace(i,'N',inplace=True)

    for i in data['NewExist']:
        if i not in [1,2]:
            data['NewExist'].replace(i,None,inplace=True)

    for column in category_cols:
        data[column]=data[column].fillna(data[column].mode()[0])

    
    # 10 New Feature Extractions
    import numpy as np
    # Apply the log transformation to the specific feature in your training data
    small_constant = 1e-10  # You can adjust this constant as needed
    # df['LogColumn'] = np.log(df['OriginalColumn'] + small_constant)
    data['Log_DisbursementGross'] = np.log1p(data['DisbursementGross'])
    data['Log_GrAppv'] = np.log1p(data['GrAppv'])
    data['Log_SBA_Appv'] = np.log1p(data['SBA_Appv'])
    data['Log_BalanceGross'] = np.log1p(data['BalanceGross'])
    data['TotalJobs'] = data['CreateJob'] + data['RetainedJob']
    #train_encoded['Loan_Efficiency'] = train_encoded['DisbursementGross'] / (train_encoded['CreateJob'] + train_encoded['RetainedJob'] + 1)
    # Calculate 'LoanToIncomeRatio' as a ratio of 'SBA_Appv' to 'DisbursementGross'
    data['IncomeToLoanRatio'] = data['DisbursementGross'] / data['SBA_Appv']
    # Calculate 'LoanToEmployeesRatio' as a ratio of 'SBA_Appv' to 'NoEmp'
    data['EmployeesToLoanRatio'] = data['NoEmp'] / data['SBA_Appv']
    # Create a binary feature to indicate loans with a balance ('BalanceGross' > 0)
    #train_encoded['HasBalance'] = (train_encoded['BalanceGross'] > 0).astype(int)
    # Calculate 'LoanPerJob' as a ratio of 'SBA_Appv' to 'TotalJobs'
    data['JobPerLoan'] = data['TotalJobs'] / data['SBA_Appv'] 
    # Calculate SBA's Gaurenteed Portion of Approved Loan
    data['Gauren_SBA_Appv'] = data['GrAppv'] / data['SBA_Appv']


    # Scaling the numerical columns
    data[numerical_columns] = scaler.transform(data[numerical_columns])                             
    
    # Target encoding the categorical columns
    data_encoded = te.transform(data[te_columns])
    data_encoded = data_encoded.add_suffix('_trg')
    data_encoded = pd.concat([data_encoded, data], axis=1)
    
    # Renaming the columns
    
    for column in te_columns:
        data_encoded[column + "_trg"].fillna(data_encoded[column + "_trg"].mean(), inplace=True)
    
    # Predicting the probabilities
    y_prob = clf.predict_proba(data_encoded[columns_to_score])
    y_pred = (y_prob[:,0] < threshold).astype(int)
    d = {
        "index": data.index,
        "label": y_pred,
        "probability_0": y_prob[:,0],
        "probability_1": y_prob[:,1],
        "threshold":threshold
    }
    #print(y_prob)
    return pd.DataFrame(d)

In [183]:
print(scoring(X_test))

         index  label  probability_0  probability_1  threshold
0            0      1       0.500004       0.499996   0.505051
1            1      0       0.639739       0.360261   0.505051
2            2      1       0.500004       0.499996   0.505051
3            3      0       0.789032       0.210968   0.505051
4            4      0       0.878069       0.121931   0.505051
...        ...    ...            ...            ...        ...
160046  160046      1       0.500004       0.499996   0.505051
160047  160047      0       0.745296       0.254704   0.505051
160048  160048      0       0.749889       0.250111   0.505051
160049  160049      1       0.500004       0.499996   0.505051
160050  160050      0       0.641459       0.358541   0.505051

[160051 rows x 5 columns]
